// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/audit.proto

package consolev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sequence  uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Actor     string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Action    string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Subject   string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// succeeded (database control change), intent, succeeded/failed/partial/rejected/unknown
	// (external command result). Intent without a result has an unknown outcome;
	// never replay the command merely because its result entry is missing.
	Outcome       string       `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	OperationId   string       `protobuf:"bytes,8,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Detail        *AuditDetail `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuditEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuditEntry) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditEntry) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AuditEntry) GetDetail() *AuditDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Safe control metadata only. No request payload, arbitrary error text,
// configuration values, comments, credentials or session tokens.
type AuditDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	RollbackOf    uint64                 `protobuf:"varint,2,opt,name=rollback_of,json=rollbackOf,proto3" json:"rollback_of,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Paused        *bool                  `protobuf:"varint,4,opt,name=paused,proto3,oneof" json:"paused,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,6,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Affected      uint64                 `protobuf:"varint,8,opt,name=affected,proto3" json:"affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditDetail) Reset() {
	*x = AuditDetail{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditDetail) ProtoMessage() {}

func (x *AuditDetail) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditDetail.ProtoReflect.Descriptor instead.
func (*AuditDetail) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditDetail) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AuditDetail) GetRollbackOf() uint64 {
	if x != nil {
		return x.RollbackOf
	}
	return 0
}

func (x *AuditDetail) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *AuditDetail) GetPaused() bool {
	if x != nil && x.Paused != nil {
		return *x.Paused
	}
	return false
}

func (x *AuditDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuditDetail) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AuditDetail) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AuditDetail) GetAffected() uint64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type AuditFilter struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Actor       string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Action      string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Subject     string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Outcome     string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	OperationId string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Inclusive start, exclusive end. Absent = unbounded.
	Start         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditFilter) Reset() {
	*x = AuditFilter{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditFilter) ProtoMessage() {}

func (x *AuditFilter) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditFilter.ProtoReflect.Descriptor instead.
func (*AuditFilter) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditFilter) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditFilter) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditFilter) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuditFilter) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditFilter) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AuditFilter) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AuditFilter) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ListAuditRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Filter *AuditFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// 0 = 100; maximum 500.
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque. Reuse exactly the same filter on every page.
	PageCursor    string `protobuf:"bytes,3,opt,name=page_cursor,json=pageCursor,proto3" json:"page_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditRequest) Reset() {
	*x = ListAuditRequest{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditRequest) ProtoMessage() {}

func (x *ListAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditRequest.ProtoReflect.Descriptor instead.
func (*ListAuditRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuditRequest) GetFilter() *AuditFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListAuditRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditRequest) GetPageCursor() string {
	if x != nil {
		return x.PageCursor
	}
	return ""
}

type ListAuditResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entries        []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageCursor string                 `protobuf:"bytes,2,opt,name=next_page_cursor,json=nextPageCursor,proto3" json:"next_page_cursor,omitempty"`
	// Starts a delta stream after the first page's consistent snapshot.
	WatchCursor   string `protobuf:"bytes,3,opt,name=watch_cursor,json=watchCursor,proto3" json:"watch_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditResponse) Reset() {
	*x = ListAuditResponse{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditResponse) ProtoMessage() {}

func (x *ListAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditResponse.ProtoReflect.Descriptor instead.
func (*ListAuditResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *ListAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAuditResponse) GetNextPageCursor() string {
	if x != nil {
		return x.NextPageCursor
	}
	return ""
}

func (x *ListAuditResponse) GetWatchCursor() string {
	if x != nil {
		return x.WatchCursor
	}
	return ""
}

type WatchAuditRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Filter *AuditFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Required. Bound to installation and filter; expired cursors fail explicitly.
	AfterCursor   string `protobuf:"bytes,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAuditRequest) Reset() {
	*x = WatchAuditRequest{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAuditRequest) ProtoMessage() {}

func (x *WatchAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAuditRequest.ProtoReflect.Descriptor instead.
func (*WatchAuditRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *WatchAuditRequest) GetFilter() *AuditFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *WatchAuditRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

type WatchAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAuditResponse) Reset() {
	*x = WatchAuditResponse{}
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAuditResponse) ProtoMessage() {}

func (x *WatchAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAuditResponse.ProtoReflect.Descriptor instead.
func (*WatchAuditResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_audit_proto_rawDescGZIP(), []int{6}
}

func (x *WatchAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *WatchAuditResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_backplanepb_console_v1_audit_proto protoreflect.FileDescriptor

const file_backplanepb_console_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\"backplanepb/console/v1/audit.proto\x12\x14backplane.console.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12!\n" +
	"\foperation_id\x18\b \x01(\tR\voperationId\x129\n" +
	"\x06detail\x18\t \x01(\v2!.backplane.console.v1.AuditDetailR\x06detail\"\xee\x01\n" +
	"\vAuditDetail\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12\x1f\n" +
	"\vrollback_of\x18\x02 \x01(\x04R\n" +
	"rollbackOf\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\x12\x1b\n" +
	"\x06paused\x18\x04 \x01(\bH\x00R\x06paused\x88\x01\x01\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1f\n" +
	"\vworkflow_id\x18\x06 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12\x1a\n" +
	"\baffected\x18\b \x01(\x04R\baffectedB\t\n" +
	"\a_paused\"\xf2\x01\n" +
	"\vAuditFilter\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\x120\n" +
	"\x05start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\x8b\x01\n" +
	"\x10ListAuditRequest\x129\n" +
	"\x06filter\x18\x01 \x01(\v2!.backplane.console.v1.AuditFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vpage_cursor\x18\x03 \x01(\tR\n" +
	"pageCursor\"\x9c\x01\n" +
	"\x11ListAuditResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .backplane.console.v1.AuditEntryR\aentries\x12(\n" +
	"\x10next_page_cursor\x18\x02 \x01(\tR\x0enextPageCursor\x12!\n" +
	"\fwatch_cursor\x18\x03 \x01(\tR\vwatchCursor\"q\n" +
	"\x11WatchAuditRequest\x129\n" +
	"\x06filter\x18\x01 \x01(\v2!.backplane.console.v1.AuditFilterR\x06filter\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\tR\vafterCursor\"h\n" +
	"\x12WatchAuditResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .backplane.console.v1.AuditEntryR\aentries\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor2\xcf\x01\n" +
	"\fAuditService\x12\\\n" +
	"\tListAudit\x12&.backplane.console.v1.ListAuditRequest\x1a'.backplane.console.v1.ListAuditResponse\x12a\n" +
	"\n" +
	"WatchAudit\x12'.backplane.console.v1.WatchAuditRequest\x1a(.backplane.console.v1.WatchAuditResponse0\x01B@Z>github.com/gopherex/backplane/backplanepb/console/v1;consolev1b\x06proto3"

var (
	file_backplanepb_console_v1_audit_proto_rawDescOnce sync.Once
	file_backplanepb_console_v1_audit_proto_rawDescData []byte
)

func file_backplanepb_console_v1_audit_proto_rawDescGZIP() []byte {
	file_backplanepb_console_v1_audit_proto_rawDescOnce.Do(func() {
		file_backplanepb_console_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_audit_proto_rawDesc), len(file_backplanepb_console_v1_audit_proto_rawDesc)))
	})
	return file_backplanepb_console_v1_audit_proto_rawDescData
}

var file_backplanepb_console_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_backplanepb_console_v1_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),            // 0: backplane.console.v1.AuditEntry
	(*AuditDetail)(nil),           // 1: backplane.console.v1.AuditDetail
	(*AuditFilter)(nil),           // 2: backplane.console.v1.AuditFilter
	(*ListAuditRequest)(nil),      // 3: backplane.console.v1.ListAuditRequest
	(*ListAuditResponse)(nil),     // 4: backplane.console.v1.ListAuditResponse
	(*WatchAuditRequest)(nil),     // 5: backplane.console.v1.WatchAuditRequest
	(*WatchAuditResponse)(nil),    // 6: backplane.console.v1.WatchAuditResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_backplanepb_console_v1_audit_proto_depIdxs = []int32{
	7,  // 0: backplane.console.v1.AuditEntry.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: backplane.console.v1.AuditEntry.detail:type_name -> backplane.console.v1.AuditDetail
	7,  // 2: backplane.console.v1.AuditFilter.start:type_name -> google.protobuf.Timestamp
	7,  // 3: backplane.console.v1.AuditFilter.end:type_name -> google.protobuf.Timestamp
	2,  // 4: backplane.console.v1.ListAuditRequest.filter:type_name -> backplane.console.v1.AuditFilter
	0,  // 5: backplane.console.v1.ListAuditResponse.entries:type_name -> backplane.console.v1.AuditEntry
	2,  // 6: backplane.console.v1.WatchAuditRequest.filter:type_name -> backplane.console.v1.AuditFilter
	0,  // 7: backplane.console.v1.WatchAuditResponse.entries:type_name -> backplane.console.v1.AuditEntry
	3,  // 8: backplane.console.v1.AuditService.ListAudit:input_type -> backplane.console.v1.ListAuditRequest
	5,  // 9: backplane.console.v1.AuditService.WatchAudit:input_type -> backplane.console.v1.WatchAuditRequest
	4,  // 10: backplane.console.v1.AuditService.ListAudit:output_type -> backplane.console.v1.ListAuditResponse
	6,  // 11: backplane.console.v1.AuditService.WatchAudit:output_type -> backplane.console.v1.WatchAuditResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_backplanepb_console_v1_audit_proto_init() }
func file_backplanepb_console_v1_audit_proto_init() {
	if File_backplanepb_console_v1_audit_proto != nil {
		return
	}
	file_backplanepb_console_v1_audit_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_audit_proto_rawDesc), len(file_backplanepb_console_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backplanepb_console_v1_audit_proto_goTypes,
		DependencyIndexes: file_backplanepb_console_v1_audit_proto_depIdxs,
		MessageInfos:      file_backplanepb_console_v1_audit_proto_msgTypes,
	}.Build()
	File_backplanepb_console_v1_audit_proto = out.File
	file_backplanepb_console_v1_audit_proto_goTypes = nil
	file_backplanepb_console_v1_audit_proto_depIdxs = nil
}
