// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/calls.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallService_CallHook_FullMethodName    = "/backplane.console.v1.CallService/CallHook"
	CallService_RunActivity_FullMethodName = "/backplane.console.v1.CallService/RunActivity"
)

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CallService runs a hook or an activity from the console with a JSON
// input (§9, §7.2) and waits for the result. Both run as short workflows
// on backplane's own task queue (backplane is a service on its SDK), with
// memo source = console:<session>: the run is in Temporal with its input,
// output and error like any other.
type CallServiceClient interface {
	// Raises a hook as its service would: the Nexus operation <Name> of
	// <service>.Hooks on endpoint <service>, handled by its binding.
	CallHook(ctx context.Context, in *CallHookRequest, opts ...grpc.CallOption) (*CallHookResponse, error)
	// Executes an activity by name on its service's task queue with the
	// ActivityCall envelope: a Temporal activity, or a child workflow for an
	// activity of kind WORKFLOW.
	RunActivity(ctx context.Context, in *RunActivityRequest, opts ...grpc.CallOption) (*RunActivityResponse, error)
}

type callServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallServiceClient(cc grpc.ClientConnInterface) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) CallHook(ctx context.Context, in *CallHookRequest, opts ...grpc.CallOption) (*CallHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallHookResponse)
	err := c.cc.Invoke(ctx, CallService_CallHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) RunActivity(ctx context.Context, in *RunActivityRequest, opts ...grpc.CallOption) (*RunActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunActivityResponse)
	err := c.cc.Invoke(ctx, CallService_RunActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
// All implementations must embed UnimplementedCallServiceServer
// for forward compatibility.
//
// CallService runs a hook or an activity from the console with a JSON
// input (§9, §7.2) and waits for the result. Both run as short workflows
// on backplane's own task queue (backplane is a service on its SDK), with
// memo source = console:<session>: the run is in Temporal with its input,
// output and error like any other.
type CallServiceServer interface {
	// Raises a hook as its service would: the Nexus operation <Name> of
	// <service>.Hooks on endpoint <service>, handled by its binding.
	CallHook(context.Context, *CallHookRequest) (*CallHookResponse, error)
	// Executes an activity by name on its service's task queue with the
	// ActivityCall envelope: a Temporal activity, or a child workflow for an
	// activity of kind WORKFLOW.
	RunActivity(context.Context, *RunActivityRequest) (*RunActivityResponse, error)
	mustEmbedUnimplementedCallServiceServer()
}

// UnimplementedCallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallServiceServer struct{}

func (UnimplementedCallServiceServer) CallHook(context.Context, *CallHookRequest) (*CallHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallHook not implemented")
}
func (UnimplementedCallServiceServer) RunActivity(context.Context, *RunActivityRequest) (*RunActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunActivity not implemented")
}
func (UnimplementedCallServiceServer) mustEmbedUnimplementedCallServiceServer() {}
func (UnimplementedCallServiceServer) testEmbeddedByValue()                     {}

// UnsafeCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServiceServer will
// result in compilation errors.
type UnsafeCallServiceServer interface {
	mustEmbedUnimplementedCallServiceServer()
}

func RegisterCallServiceServer(s grpc.ServiceRegistrar, srv CallServiceServer) {
	// If the following call panics, it indicates UnimplementedCallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallService_ServiceDesc, srv)
}

func _CallService_CallHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CallHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_CallHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CallHook(ctx, req.(*CallHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_RunActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).RunActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallService_RunActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).RunActivity(ctx, req.(*RunActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallService_ServiceDesc is the grpc.ServiceDesc for CallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallHook",
			Handler:    _CallService_CallHook_Handler,
		},
		{
			MethodName: "RunActivity",
			Handler:    _CallService_RunActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backplanepb/console/v1/calls.proto",
}
