// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/catalog.proto

package consolev1

import (
	v1 "github.com/gopherex/backplane/backplanepb/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a service is doing, from its instances.
type ServiceHealth int32

const (
	ServiceHealth_SERVICE_HEALTH_UNSPECIFIED ServiceHealth = 0
	// Every instance is registered and passing.
	ServiceHealth_SERVICE_HEALTH_HEALTHY ServiceHealth = 1
	// Some instances are passing, some are not.
	ServiceHealth_SERVICE_HEALTH_DEGRADED ServiceHealth = 2
	// No instance is passing (or there are none).
	ServiceHealth_SERVICE_HEALTH_DOWN ServiceHealth = 3
)

// Enum value maps for ServiceHealth.
var (
	ServiceHealth_name = map[int32]string{
		0: "SERVICE_HEALTH_UNSPECIFIED",
		1: "SERVICE_HEALTH_HEALTHY",
		2: "SERVICE_HEALTH_DEGRADED",
		3: "SERVICE_HEALTH_DOWN",
	}
	ServiceHealth_value = map[string]int32{
		"SERVICE_HEALTH_UNSPECIFIED": 0,
		"SERVICE_HEALTH_HEALTHY":     1,
		"SERVICE_HEALTH_DEGRADED":    2,
		"SERVICE_HEALTH_DOWN":        3,
	}
)

func (x ServiceHealth) Enum() *ServiceHealth {
	p := new(ServiceHealth)
	*p = x
	return p
}

func (x ServiceHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_console_v1_catalog_proto_enumTypes[0].Descriptor()
}

func (ServiceHealth) Type() protoreflect.EnumType {
	return &file_backplanepb_console_v1_catalog_proto_enumTypes[0]
}

func (x ServiceHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceHealth.Descriptor instead.
func (ServiceHealth) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{0}
}

type ServiceSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of the latest manifest (the highest a live instance runs).
	LatestVersion string `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// Every version a manifest is known for, highest first.
	Versions []string `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	// Instances known (catalog or published state).
	Instances uint32 `protobuf:"varint,4,opt,name=instances,proto3" json:"instances,omitempty"`
	// Registered and passing the health check.
	Healthy uint32        `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Health  ServiceHealth `protobuf:"varint,6,opt,name=health,proto3,enum=backplane.console.v1.ServiceHealth" json:"health,omitempty"`
	// The latest manifest declares an internal API (the relay forwards to it).
	InternalApi bool `protobuf:"varint,7,opt,name=internal_api,json=internalApi,proto3" json:"internal_api,omitempty"`
	// The latest manifest declares a UI bundle (a console plugin).
	Ui            bool `protobuf:"varint,8,opt,name=ui,proto3" json:"ui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSummary) Reset() {
	*x = ServiceSummary{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSummary) ProtoMessage() {}

func (x *ServiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSummary.ProtoReflect.Descriptor instead.
func (*ServiceSummary) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSummary) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *ServiceSummary) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ServiceSummary) GetInstances() uint32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *ServiceSummary) GetHealthy() uint32 {
	if x != nil {
		return x.Healthy
	}
	return 0
}

func (x *ServiceSummary) GetHealth() ServiceHealth {
	if x != nil {
		return x.Health
	}
	return ServiceHealth_SERVICE_HEALTH_UNSPECIFIED
}

func (x *ServiceSummary) GetInternalApi() bool {
	if x != nil {
		return x.InternalApi
	}
	return false
}

func (x *ServiceSummary) GetUi() bool {
	if x != nil {
		return x.Ui
	}
	return false
}

type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The SDK's published state; unset when only the catalog knows the
	// instance.
	State *v1.InstanceState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// In the Consul catalog.
	Registered bool `protobuf:"varint,3,opt,name=registered,proto3" json:"registered,omitempty"`
	// The catalog health check passes.
	Healthy bool `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Where public traffic goes (catalog registration); port 0 without
	// managed routes.
	Address       string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32   `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Tags          []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetState() *v1.InstanceState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Instance) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *Instance) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Instance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Instance) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Instance) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{2}
}

type ListServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted by name.
	Services []*ServiceSummary `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	// Index of the registry snapshot the answer comes from.
	Index         uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesResponse) GetServices() []*ServiceSummary {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetServiceResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Summary *ServiceSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// The latest manifest (see ServiceSummary.latest_version).
	Latest *v1.Manifest `protobuf:"bytes,2,opt,name=latest,proto3" json:"latest,omitempty"`
	// Every known manifest, highest version first.
	Manifests []*v1.Manifest `protobuf:"bytes,3,rep,name=manifests,proto3" json:"manifests,omitempty"`
	// Sorted by id.
	Instances     []*Instance `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	Index         uint64      `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceResponse) GetSummary() *ServiceSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetServiceResponse) GetLatest() *v1.Manifest {
	if x != nil {
		return x.Latest
	}
	return nil
}

func (x *GetServiceResponse) GetManifests() []*v1.Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *GetServiceResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *GetServiceResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WatchCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCatalogRequest) Reset() {
	*x = WatchCatalogRequest{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCatalogRequest) ProtoMessage() {}

func (x *WatchCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCatalogRequest.ProtoReflect.Descriptor instead.
func (*WatchCatalogRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{6}
}

type WatchCatalogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted by name.
	Services      []*ServiceSummary `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Index         uint64            `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCatalogResponse) Reset() {
	*x = WatchCatalogResponse{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCatalogResponse) ProtoMessage() {}

func (x *WatchCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCatalogResponse.ProtoReflect.Descriptor instead.
func (*WatchCatalogResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *WatchCatalogResponse) GetServices() []*ServiceSummary {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *WatchCatalogResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{8}
}

type Plugin struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Content hash of the bundle (manifest ui.hash).
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Major of the UI SDK the bundle is built against; the shell loads only
	// its own major.
	SdkMajor uint32 `protobuf:"varint,3,opt,name=sdk_major,json=sdkMajor,proto3" json:"sdk_major,omitempty"`
	// Where the console serves the bundle: <console>/plugins/<service>/<hash>/
	// relative to the console's base.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// A live instance serves this bundle: without one the plugin is not in
	// the navigation (its service card stays).
	Available     bool `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *Plugin) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Plugin) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Plugin) GetSdkMajor() uint32 {
	if x != nil {
		return x.SdkMajor
	}
	return 0
}

func (x *Plugin) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Plugin) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListPluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sorted by service.
	Plugins       []*Plugin `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ListPluginsResponse) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

var File_backplanepb_console_v1_catalog_proto protoreflect.FileDescriptor

const file_backplanepb_console_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"$backplanepb/console/v1/catalog.proto\x12\x14backplane.console.v1\x1a\x1dbackplanepb/v1/instance.proto\x1a\x1dbackplanepb/v1/manifest.proto\"\x8f\x02\n" +
	"\x0eServiceSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversions\x12\x1c\n" +
	"\tinstances\x18\x04 \x01(\rR\tinstances\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\rR\ahealthy\x12;\n" +
	"\x06health\x18\x06 \x01(\x0e2#.backplane.console.v1.ServiceHealthR\x06health\x12!\n" +
	"\finternal_api\x18\a \x01(\bR\vinternalApi\x12\x0e\n" +
	"\x02ui\x18\b \x01(\bR\x02ui\"\xc9\x01\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x05state\x18\x02 \x01(\v2\x1b.backplane.v1.InstanceStateR\x05state\x12\x1e\n" +
	"\n" +
	"registered\x18\x03 \x01(\bR\n" +
	"registered\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\x15\n" +
	"\x13ListServicesRequest\"n\n" +
	"\x14ListServicesResponse\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.backplane.console.v1.ServiceSummaryR\bservices\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"'\n" +
	"\x11GetServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8e\x02\n" +
	"\x12GetServiceResponse\x12>\n" +
	"\asummary\x18\x01 \x01(\v2$.backplane.console.v1.ServiceSummaryR\asummary\x12.\n" +
	"\x06latest\x18\x02 \x01(\v2\x16.backplane.v1.ManifestR\x06latest\x124\n" +
	"\tmanifests\x18\x03 \x03(\v2\x16.backplane.v1.ManifestR\tmanifests\x12<\n" +
	"\tinstances\x18\x04 \x03(\v2\x1e.backplane.console.v1.InstanceR\tinstances\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x04R\x05index\"\x15\n" +
	"\x13WatchCatalogRequest\"n\n" +
	"\x14WatchCatalogResponse\x12@\n" +
	"\bservices\x18\x01 \x03(\v2$.backplane.console.v1.ServiceSummaryR\bservices\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"\x14\n" +
	"\x12ListPluginsRequest\"\x85\x01\n" +
	"\x06Plugin\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1b\n" +
	"\tsdk_major\x18\x03 \x01(\rR\bsdkMajor\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\"M\n" +
	"\x13ListPluginsResponse\x126\n" +
	"\aplugins\x18\x01 \x03(\v2\x1c.backplane.console.v1.PluginR\aplugins*\x81\x01\n" +
	"\rServiceHealth\x12\x1e\n" +
	"\x1aSERVICE_HEALTH_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_HEALTH_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17SERVICE_HEALTH_DEGRADED\x10\x02\x12\x17\n" +
	"\x13SERVICE_HEALTH_DOWN\x10\x032\xa5\x03\n" +
	"\x0eCatalogService\x12e\n" +
	"\fListServices\x12).backplane.console.v1.ListServicesRequest\x1a*.backplane.console.v1.ListServicesResponse\x12_\n" +
	"\n" +
	"GetService\x12'.backplane.console.v1.GetServiceRequest\x1a(.backplane.console.v1.GetServiceResponse\x12g\n" +
	"\fWatchCatalog\x12).backplane.console.v1.WatchCatalogRequest\x1a*.backplane.console.v1.WatchCatalogResponse0\x01\x12b\n" +
	"\vListPlugins\x12(.backplane.console.v1.ListPluginsRequest\x1a).backplane.console.v1.ListPluginsResponseB@Z>github.com/gopherex/backplane/backplanepb/console/v1;consolev1b\x06proto3"

var (
	file_backplanepb_console_v1_catalog_proto_rawDescOnce sync.Once
	file_backplanepb_console_v1_catalog_proto_rawDescData []byte
)

func file_backplanepb_console_v1_catalog_proto_rawDescGZIP() []byte {
	file_backplanepb_console_v1_catalog_proto_rawDescOnce.Do(func() {
		file_backplanepb_console_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_catalog_proto_rawDesc), len(file_backplanepb_console_v1_catalog_proto_rawDesc)))
	})
	return file_backplanepb_console_v1_catalog_proto_rawDescData
}

var file_backplanepb_console_v1_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backplanepb_console_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_backplanepb_console_v1_catalog_proto_goTypes = []any{
	(ServiceHealth)(0),           // 0: backplane.console.v1.ServiceHealth
	(*ServiceSummary)(nil),       // 1: backplane.console.v1.ServiceSummary
	(*Instance)(nil),             // 2: backplane.console.v1.Instance
	(*ListServicesRequest)(nil),  // 3: backplane.console.v1.ListServicesRequest
	(*ListServicesResponse)(nil), // 4: backplane.console.v1.ListServicesResponse
	(*GetServiceRequest)(nil),    // 5: backplane.console.v1.GetServiceRequest
	(*GetServiceResponse)(nil),   // 6: backplane.console.v1.GetServiceResponse
	(*WatchCatalogRequest)(nil),  // 7: backplane.console.v1.WatchCatalogRequest
	(*WatchCatalogResponse)(nil), // 8: backplane.console.v1.WatchCatalogResponse
	(*ListPluginsRequest)(nil),   // 9: backplane.console.v1.ListPluginsRequest
	(*Plugin)(nil),               // 10: backplane.console.v1.Plugin
	(*ListPluginsResponse)(nil),  // 11: backplane.console.v1.ListPluginsResponse
	(*v1.InstanceState)(nil),     // 12: backplane.v1.InstanceState
	(*v1.Manifest)(nil),          // 13: backplane.v1.Manifest
}
var file_backplanepb_console_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: backplane.console.v1.ServiceSummary.health:type_name -> backplane.console.v1.ServiceHealth
	12, // 1: backplane.console.v1.Instance.state:type_name -> backplane.v1.InstanceState
	1,  // 2: backplane.console.v1.ListServicesResponse.services:type_name -> backplane.console.v1.ServiceSummary
	1,  // 3: backplane.console.v1.GetServiceResponse.summary:type_name -> backplane.console.v1.ServiceSummary
	13, // 4: backplane.console.v1.GetServiceResponse.latest:type_name -> backplane.v1.Manifest
	13, // 5: backplane.console.v1.GetServiceResponse.manifests:type_name -> backplane.v1.Manifest
	2,  // 6: backplane.console.v1.GetServiceResponse.instances:type_name -> backplane.console.v1.Instance
	1,  // 7: backplane.console.v1.WatchCatalogResponse.services:type_name -> backplane.console.v1.ServiceSummary
	10, // 8: backplane.console.v1.ListPluginsResponse.plugins:type_name -> backplane.console.v1.Plugin
	3,  // 9: backplane.console.v1.CatalogService.ListServices:input_type -> backplane.console.v1.ListServicesRequest
	5,  // 10: backplane.console.v1.CatalogService.GetService:input_type -> backplane.console.v1.GetServiceRequest
	7,  // 11: backplane.console.v1.CatalogService.WatchCatalog:input_type -> backplane.console.v1.WatchCatalogRequest
	9,  // 12: backplane.console.v1.CatalogService.ListPlugins:input_type -> backplane.console.v1.ListPluginsRequest
	4,  // 13: backplane.console.v1.CatalogService.ListServices:output_type -> backplane.console.v1.ListServicesResponse
	6,  // 14: backplane.console.v1.CatalogService.GetService:output_type -> backplane.console.v1.GetServiceResponse
	8,  // 15: backplane.console.v1.CatalogService.WatchCatalog:output_type -> backplane.console.v1.WatchCatalogResponse
	11, // 16: backplane.console.v1.CatalogService.ListPlugins:output_type -> backplane.console.v1.ListPluginsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_backplanepb_console_v1_catalog_proto_init() }
func file_backplanepb_console_v1_catalog_proto_init() {
	if File_backplanepb_console_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_catalog_proto_rawDesc), len(file_backplanepb_console_v1_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backplanepb_console_v1_catalog_proto_goTypes,
		DependencyIndexes: file_backplanepb_console_v1_catalog_proto_depIdxs,
		EnumInfos:         file_backplanepb_console_v1_catalog_proto_enumTypes,
		MessageInfos:      file_backplanepb_console_v1_catalog_proto_msgTypes,
	}.Build()
	File_backplanepb_console_v1_catalog_proto = out.File
	file_backplanepb_console_v1_catalog_proto_goTypes = nil
	file_backplanepb_console_v1_catalog_proto_depIdxs = nil
}
