// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/config.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetConfig_FullMethodName        = "/backplane.console.v1.ConfigService/GetConfig"
	ConfigService_ListRevisions_FullMethodName    = "/backplane.console.v1.ConfigService/ListRevisions"
	ConfigService_ValidateOverride_FullMethodName = "/backplane.console.v1.ConfigService/ValidateOverride"
	ConfigService_SaveRevision_FullMethodName     = "/backplane.console.v1.ConfigService/SaveRevision"
	ConfigService_Rollback_FullMethodName         = "/backplane.console.v1.ConfigService/Rollback"
	ConfigService_WatchConfig_FullMethodName      = "/backplane.console.v1.ConfigService/WatchConfig"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService is the console's view of Live configuration (§5): the
// override of a service's Live fields kept as revisions in PostgreSQL and
// delivered to Consul KV config/<service>/.
//
// An override is a map from a Live path of the service's manifest
// (config.live, dot-separated: "greeter.suffix") to the JSON text of its
// value ("\"!\"", "5", "{\"max\":10}"). Only Live paths may be overridden;
// a Live field is replaced whole. A path absent from the override takes
// its value from the instance's own layers (defaults, file, env).
type ConfigServiceClient interface {
	// GetConfig is the service's configuration: schema, Live paths, the
	// current revision and what every live instance runs with.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// ListRevisions pages through the revisions, newest first.
	ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error)
	// ValidateOverride is SaveRevision without saving: the violations it
	// would be rejected with.
	ValidateOverride(ctx context.Context, in *ValidateOverrideRequest, opts ...grpc.CallOption) (*ValidateOverrideResponse, error)
	// SaveRevision validates the override and, when valid, saves it as the
	// next revision and delivers it to Consul KV. Invalid: nothing is saved,
	// violations say why.
	SaveRevision(ctx context.Context, in *SaveRevisionRequest, opts ...grpc.CallOption) (*SaveRevisionResponse, error)
	// Rollback saves a new revision with the values of an older one
	// (rollback_of), validated as any save.
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// WatchConfig streams the service's configuration: the current one
	// first, then a new one whenever the service's instances, manifests or revision
	// change.
	WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchConfigResponse], error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRevisionsResponse)
	err := c.cc.Invoke(ctx, ConfigService_ListRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ValidateOverride(ctx context.Context, in *ValidateOverrideRequest, opts ...grpc.CallOption) (*ValidateOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOverrideResponse)
	err := c.cc.Invoke(ctx, ConfigService_ValidateOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) SaveRevision(ctx context.Context, in *SaveRevisionRequest, opts ...grpc.CallOption) (*SaveRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRevisionResponse)
	err := c.cc.Invoke(ctx, ConfigService_SaveRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ConfigService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchConfigResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigService_ServiceDesc.Streams[0], ConfigService_WatchConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfigRequest, WatchConfigResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigService_WatchConfigClient = grpc.ServerStreamingClient[WatchConfigResponse]

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService is the console's view of Live configuration (§5): the
// override of a service's Live fields kept as revisions in PostgreSQL and
// delivered to Consul KV config/<service>/.
//
// An override is a map from a Live path of the service's manifest
// (config.live, dot-separated: "greeter.suffix") to the JSON text of its
// value ("\"!\"", "5", "{\"max\":10}"). Only Live paths may be overridden;
// a Live field is replaced whole. A path absent from the override takes
// its value from the instance's own layers (defaults, file, env).
type ConfigServiceServer interface {
	// GetConfig is the service's configuration: schema, Live paths, the
	// current revision and what every live instance runs with.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// ListRevisions pages through the revisions, newest first.
	ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error)
	// ValidateOverride is SaveRevision without saving: the violations it
	// would be rejected with.
	ValidateOverride(context.Context, *ValidateOverrideRequest) (*ValidateOverrideResponse, error)
	// SaveRevision validates the override and, when valid, saves it as the
	// next revision and delivers it to Consul KV. Invalid: nothing is saved,
	// violations say why.
	SaveRevision(context.Context, *SaveRevisionRequest) (*SaveRevisionResponse, error)
	// Rollback saves a new revision with the values of an older one
	// (rollback_of), validated as any save.
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// WatchConfig streams the service's configuration: the current one
	// first, then a new one whenever the service's instances, manifests or revision
	// change.
	WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[WatchConfigResponse]) error
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRevisions not implemented")
}
func (UnimplementedConfigServiceServer) ValidateOverride(context.Context, *ValidateOverrideRequest) (*ValidateOverrideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateOverride not implemented")
}
func (UnimplementedConfigServiceServer) SaveRevision(context.Context, *SaveRevisionRequest) (*SaveRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRevision not implemented")
}
func (UnimplementedConfigServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedConfigServiceServer) WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[WatchConfigResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ListRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListRevisions(ctx, req.(*ListRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ValidateOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ValidateOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ValidateOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ValidateOverride(ctx, req.(*ValidateOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_SaveRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).SaveRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_SaveRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).SaveRevision(ctx, req.(*SaveRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServiceServer).WatchConfig(m, &grpc.GenericServerStream[WatchConfigRequest, WatchConfigResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigService_WatchConfigServer = grpc.ServerStreamingServer[WatchConfigResponse]

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ConfigService_GetConfig_Handler,
		},
		{
			MethodName: "ListRevisions",
			Handler:    _ConfigService_ListRevisions_Handler,
		},
		{
			MethodName: "ValidateOverride",
			Handler:    _ConfigService_ValidateOverride_Handler,
		},
		{
			MethodName: "SaveRevision",
			Handler:    _ConfigService_SaveRevision_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _ConfigService_Rollback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _ConfigService_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backplanepb/console/v1/config.proto",
}
