// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/rules.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuleService_ListRules_FullMethodName        = "/backplane.console.v1.RuleService/ListRules"
	RuleService_GetRule_FullMethodName          = "/backplane.console.v1.RuleService/GetRule"
	RuleService_ListRuleVersions_FullMethodName = "/backplane.console.v1.RuleService/ListRuleVersions"
	RuleService_ValidateRule_FullMethodName     = "/backplane.console.v1.RuleService/ValidateRule"
	RuleService_SaveRule_FullMethodName         = "/backplane.console.v1.RuleService/SaveRule"
	RuleService_RollbackRule_FullMethodName     = "/backplane.console.v1.RuleService/RollbackRule"
	RuleService_DeleteRule_FullMethodName       = "/backplane.console.v1.RuleService/DeleteRule"
	RuleService_PauseRule_FullMethodName        = "/backplane.console.v1.RuleService/PauseRule"
	RuleService_ResumeRule_FullMethodName       = "/backplane.console.v1.RuleService/ResumeRule"
	RuleService_ParseRule_FullMethodName        = "/backplane.console.v1.RuleService/ParseRule"
	RuleService_FormatRule_FullMethodName       = "/backplane.console.v1.RuleService/FormatRule"
	RuleService_WatchRules_FullMethodName       = "/backplane.console.v1.RuleService/WatchRules"
	RuleService_TestRule_FullMethodName         = "/backplane.console.v1.RuleService/TestRule"
	RuleService_ListRuleRuns_FullMethodName     = "/backplane.console.v1.RuleService/ListRuleRuns"
	RuleService_GetRuleRun_FullMethodName       = "/backplane.console.v1.RuleService/GetRuleRun"
	RuleService_CancelRuleRun_FullMethodName    = "/backplane.console.v1.RuleService/CancelRuleRun"
)

// RuleServiceClient is the client API for RuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuleService is the console's view of rules (§8.1): a binding whose source
// is an event instead of a hook — same steps, same executor, no result.
// A rule is identified by a uuid; its definition is versioned like a
// binding's (a delete is a tombstone version), its pause is a flag outside
// the versions.
//
// Runs are workflows on backplane's task queue with id
// rule/<id>/<ce-id> (a test run: test/rule/<id>/<uuid>): TestRule,
// ListRuleRuns, GetRuleRun, CancelRuleRun.
type RuleServiceClient interface {
	// ListRules is every rule with its current version, deleted ones
	// included (their current version is the tombstone).
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	// GetRule is one version of a rule: the current one by default.
	GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error)
	// ListRuleVersions pages through a rule's versions, newest first.
	ListRuleVersions(ctx context.Context, in *ListRuleVersionsRequest, opts ...grpc.CallOption) (*ListRuleVersionsResponse, error)
	// ValidateRule is SaveRule without saving: the violations it would be
	// rejected with.
	ValidateRule(ctx context.Context, in *ValidateRuleRequest, opts ...grpc.CallOption) (*ValidateRuleResponse, error)
	// SaveRule validates the definition and, when valid, saves it as the
	// next version of the rule (a new rule without id). Invalid: nothing is
	// saved, violations say why.
	SaveRule(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error)
	// RollbackRule saves a new version with the name and definition of an
	// older one (rollback_of), validated as any save.
	RollbackRule(ctx context.Context, in *RollbackRuleRequest, opts ...grpc.CallOption) (*RollbackRuleResponse, error)
	// DeleteRule saves a tombstone version: the rule stops, the history
	// stays.
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
	// PauseRule stops starting runs for the rule's events until resumed.
	PauseRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*PauseRuleResponse, error)
	// ResumeRule undoes PauseRule.
	ResumeRule(ctx context.Context, in *ResumeRuleRequest, opts ...grpc.CallOption) (*ResumeRuleResponse, error)
	// ParseRule reads the text form of a rule (§8.1).
	ParseRule(ctx context.Context, in *ParseRuleRequest, opts ...grpc.CallOption) (*ParseRuleResponse, error)
	// FormatRule writes the text form of a definition; ParseRule reads it
	// back into the same definition.
	FormatRule(ctx context.Context, in *FormatRuleRequest, opts ...grpc.CallOption) (*FormatRuleResponse, error)
	// WatchRules streams ListRules: now, then again whenever it changes.
	WatchRules(ctx context.Context, in *WatchRulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRulesResponse], error)
	// TestRule runs a rule on a sample event: the definition is compiled
	// against the latest manifests, `when` is evaluated on the event and,
	// when it matches (and not dry_run), a test run starts — workflow id
	// test/rule/<id>/<uuid> (draft instead of <id> for an unsaved
	// definition) — and the call waits for its end.
	TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error)
	// ListRuleRuns is a rule's runs, newest first (Temporal visibility,
	// workflow id prefix rule/<id>/ or test/rule/<id>/).
	ListRuleRuns(ctx context.Context, in *ListRuleRunsRequest, opts ...grpc.CallOption) (*ListRuleRunsResponse, error)
	// GetRuleRun is one run of the rule: status, input, result or failure,
	// pending activities and history.
	GetRuleRun(ctx context.Context, in *GetRuleRunRequest, opts ...grpc.CallOption) (*GetRuleRunResponse, error)
	// CancelRuleRun requests cancellation of a run of the rule.
	CancelRuleRun(ctx context.Context, in *CancelRuleRunRequest, opts ...grpc.CallOption) (*CancelRuleRunResponse, error)
}

type ruleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleServiceClient(cc grpc.ClientConnInterface) RuleServiceClient {
	return &ruleServiceClient{cc}
}

func (c *ruleServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, RuleService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_GetRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ListRuleVersions(ctx context.Context, in *ListRuleVersionsRequest, opts ...grpc.CallOption) (*ListRuleVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuleVersionsResponse)
	err := c.cc.Invoke(ctx, RuleService_ListRuleVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ValidateRule(ctx context.Context, in *ValidateRuleRequest, opts ...grpc.CallOption) (*ValidateRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_ValidateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) SaveRule(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_SaveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) RollbackRule(ctx context.Context, in *RollbackRuleRequest, opts ...grpc.CallOption) (*RollbackRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_RollbackRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) PauseRule(ctx context.Context, in *PauseRuleRequest, opts ...grpc.CallOption) (*PauseRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_PauseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ResumeRule(ctx context.Context, in *ResumeRuleRequest, opts ...grpc.CallOption) (*ResumeRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_ResumeRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ParseRule(ctx context.Context, in *ParseRuleRequest, opts ...grpc.CallOption) (*ParseRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_ParseRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) FormatRule(ctx context.Context, in *FormatRuleRequest, opts ...grpc.CallOption) (*FormatRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormatRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_FormatRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) WatchRules(ctx context.Context, in *WatchRulesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRulesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuleService_ServiceDesc.Streams[0], RuleService_WatchRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRulesRequest, WatchRulesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuleService_WatchRulesClient = grpc.ServerStreamingClient[WatchRulesResponse]

func (c *ruleServiceClient) TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_TestRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ListRuleRuns(ctx context.Context, in *ListRuleRunsRequest, opts ...grpc.CallOption) (*ListRuleRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuleRunsResponse)
	err := c.cc.Invoke(ctx, RuleService_ListRuleRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetRuleRun(ctx context.Context, in *GetRuleRunRequest, opts ...grpc.CallOption) (*GetRuleRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleRunResponse)
	err := c.cc.Invoke(ctx, RuleService_GetRuleRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) CancelRuleRun(ctx context.Context, in *CancelRuleRunRequest, opts ...grpc.CallOption) (*CancelRuleRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRuleRunResponse)
	err := c.cc.Invoke(ctx, RuleService_CancelRuleRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServiceServer is the server API for RuleService service.
// All implementations must embed UnimplementedRuleServiceServer
// for forward compatibility.
//
// RuleService is the console's view of rules (§8.1): a binding whose source
// is an event instead of a hook — same steps, same executor, no result.
// A rule is identified by a uuid; its definition is versioned like a
// binding's (a delete is a tombstone version), its pause is a flag outside
// the versions.
//
// Runs are workflows on backplane's task queue with id
// rule/<id>/<ce-id> (a test run: test/rule/<id>/<uuid>): TestRule,
// ListRuleRuns, GetRuleRun, CancelRuleRun.
type RuleServiceServer interface {
	// ListRules is every rule with its current version, deleted ones
	// included (their current version is the tombstone).
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	// GetRule is one version of a rule: the current one by default.
	GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	// ListRuleVersions pages through a rule's versions, newest first.
	ListRuleVersions(context.Context, *ListRuleVersionsRequest) (*ListRuleVersionsResponse, error)
	// ValidateRule is SaveRule without saving: the violations it would be
	// rejected with.
	ValidateRule(context.Context, *ValidateRuleRequest) (*ValidateRuleResponse, error)
	// SaveRule validates the definition and, when valid, saves it as the
	// next version of the rule (a new rule without id). Invalid: nothing is
	// saved, violations say why.
	SaveRule(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error)
	// RollbackRule saves a new version with the name and definition of an
	// older one (rollback_of), validated as any save.
	RollbackRule(context.Context, *RollbackRuleRequest) (*RollbackRuleResponse, error)
	// DeleteRule saves a tombstone version: the rule stops, the history
	// stays.
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	// PauseRule stops starting runs for the rule's events until resumed.
	PauseRule(context.Context, *PauseRuleRequest) (*PauseRuleResponse, error)
	// ResumeRule undoes PauseRule.
	ResumeRule(context.Context, *ResumeRuleRequest) (*ResumeRuleResponse, error)
	// ParseRule reads the text form of a rule (§8.1).
	ParseRule(context.Context, *ParseRuleRequest) (*ParseRuleResponse, error)
	// FormatRule writes the text form of a definition; ParseRule reads it
	// back into the same definition.
	FormatRule(context.Context, *FormatRuleRequest) (*FormatRuleResponse, error)
	// WatchRules streams ListRules: now, then again whenever it changes.
	WatchRules(*WatchRulesRequest, grpc.ServerStreamingServer[WatchRulesResponse]) error
	// TestRule runs a rule on a sample event: the definition is compiled
	// against the latest manifests, `when` is evaluated on the event and,
	// when it matches (and not dry_run), a test run starts — workflow id
	// test/rule/<id>/<uuid> (draft instead of <id> for an unsaved
	// definition) — and the call waits for its end.
	TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error)
	// ListRuleRuns is a rule's runs, newest first (Temporal visibility,
	// workflow id prefix rule/<id>/ or test/rule/<id>/).
	ListRuleRuns(context.Context, *ListRuleRunsRequest) (*ListRuleRunsResponse, error)
	// GetRuleRun is one run of the rule: status, input, result or failure,
	// pending activities and history.
	GetRuleRun(context.Context, *GetRuleRunRequest) (*GetRuleRunResponse, error)
	// CancelRuleRun requests cancellation of a run of the rule.
	CancelRuleRun(context.Context, *CancelRuleRunRequest) (*CancelRuleRunResponse, error)
	mustEmbedUnimplementedRuleServiceServer()
}

// UnimplementedRuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleServiceServer struct{}

func (UnimplementedRuleServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedRuleServiceServer) GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedRuleServiceServer) ListRuleVersions(context.Context, *ListRuleVersionsRequest) (*ListRuleVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuleVersions not implemented")
}
func (UnimplementedRuleServiceServer) ValidateRule(context.Context, *ValidateRuleRequest) (*ValidateRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRule not implemented")
}
func (UnimplementedRuleServiceServer) SaveRule(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRule not implemented")
}
func (UnimplementedRuleServiceServer) RollbackRule(context.Context, *RollbackRuleRequest) (*RollbackRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackRule not implemented")
}
func (UnimplementedRuleServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedRuleServiceServer) PauseRule(context.Context, *PauseRuleRequest) (*PauseRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseRule not implemented")
}
func (UnimplementedRuleServiceServer) ResumeRule(context.Context, *ResumeRuleRequest) (*ResumeRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRule not implemented")
}
func (UnimplementedRuleServiceServer) ParseRule(context.Context, *ParseRuleRequest) (*ParseRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseRule not implemented")
}
func (UnimplementedRuleServiceServer) FormatRule(context.Context, *FormatRuleRequest) (*FormatRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FormatRule not implemented")
}
func (UnimplementedRuleServiceServer) WatchRules(*WatchRulesRequest, grpc.ServerStreamingServer[WatchRulesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchRules not implemented")
}
func (UnimplementedRuleServiceServer) TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRule not implemented")
}
func (UnimplementedRuleServiceServer) ListRuleRuns(context.Context, *ListRuleRunsRequest) (*ListRuleRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuleRuns not implemented")
}
func (UnimplementedRuleServiceServer) GetRuleRun(context.Context, *GetRuleRunRequest) (*GetRuleRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleRun not implemented")
}
func (UnimplementedRuleServiceServer) CancelRuleRun(context.Context, *CancelRuleRunRequest) (*CancelRuleRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRuleRun not implemented")
}
func (UnimplementedRuleServiceServer) mustEmbedUnimplementedRuleServiceServer() {}
func (UnimplementedRuleServiceServer) testEmbeddedByValue()                     {}

// UnsafeRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleServiceServer will
// result in compilation errors.
type UnsafeRuleServiceServer interface {
	mustEmbedUnimplementedRuleServiceServer()
}

func RegisterRuleServiceServer(s grpc.ServiceRegistrar, srv RuleServiceServer) {
	// If the following call panics, it indicates UnimplementedRuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleService_ServiceDesc, srv)
}

func _RuleService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetRule(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ListRuleVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuleVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ListRuleVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ListRuleVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ListRuleVersions(ctx, req.(*ListRuleVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ValidateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ValidateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ValidateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ValidateRule(ctx, req.(*ValidateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_SaveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).SaveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_SaveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).SaveRule(ctx, req.(*SaveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_RollbackRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).RollbackRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_RollbackRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).RollbackRule(ctx, req.(*RollbackRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_PauseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).PauseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_PauseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).PauseRule(ctx, req.(*PauseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ResumeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ResumeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ResumeRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ResumeRule(ctx, req.(*ResumeRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ParseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ParseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ParseRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ParseRule(ctx, req.(*ParseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_FormatRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).FormatRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_FormatRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).FormatRule(ctx, req.(*FormatRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_WatchRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRulesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuleServiceServer).WatchRules(m, &grpc.GenericServerStream[WatchRulesRequest, WatchRulesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuleService_WatchRulesServer = grpc.ServerStreamingServer[WatchRulesResponse]

func _RuleService_TestRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).TestRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_TestRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).TestRule(ctx, req.(*TestRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ListRuleRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuleRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ListRuleRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_ListRuleRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ListRuleRuns(ctx, req.(*ListRuleRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetRuleRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetRuleRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetRuleRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetRuleRun(ctx, req.(*GetRuleRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_CancelRuleRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRuleRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).CancelRuleRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_CancelRuleRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).CancelRuleRun(ctx, req.(*CancelRuleRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleService_ServiceDesc is the grpc.ServiceDesc for RuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.RuleService",
	HandlerType: (*RuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _RuleService_ListRules_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _RuleService_GetRule_Handler,
		},
		{
			MethodName: "ListRuleVersions",
			Handler:    _RuleService_ListRuleVersions_Handler,
		},
		{
			MethodName: "ValidateRule",
			Handler:    _RuleService_ValidateRule_Handler,
		},
		{
			MethodName: "SaveRule",
			Handler:    _RuleService_SaveRule_Handler,
		},
		{
			MethodName: "RollbackRule",
			Handler:    _RuleService_RollbackRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _RuleService_DeleteRule_Handler,
		},
		{
			MethodName: "PauseRule",
			Handler:    _RuleService_PauseRule_Handler,
		},
		{
			MethodName: "ResumeRule",
			Handler:    _RuleService_ResumeRule_Handler,
		},
		{
			MethodName: "ParseRule",
			Handler:    _RuleService_ParseRule_Handler,
		},
		{
			MethodName: "FormatRule",
			Handler:    _RuleService_FormatRule_Handler,
		},
		{
			MethodName: "TestRule",
			Handler:    _RuleService_TestRule_Handler,
		},
		{
			MethodName: "ListRuleRuns",
			Handler:    _RuleService_ListRuleRuns_Handler,
		},
		{
			MethodName: "GetRuleRun",
			Handler:    _RuleService_GetRuleRun_Handler,
		},
		{
			MethodName: "CancelRuleRun",
			Handler:    _RuleService_CancelRuleRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRules",
			Handler:       _RuleService_WatchRules_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backplanepb/console/v1/rules.proto",
}
