// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/rules.proto

package consolev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleState is whether a rule runs.
type RuleState int32

const (
	RuleState_RULE_STATE_UNSPECIFIED RuleState = 0
	// Runs on every matching event.
	RuleState_RULE_STATE_ACTIVE RuleState = 1
	// Paused: no runs start.
	RuleState_RULE_STATE_PAUSED RuleState = 2
	// The current version is a tombstone.
	RuleState_RULE_STATE_DELETED RuleState = 3
	// The current definition no longer compiles against the latest
	// manifests: no runs start until it is fixed. Rule.violations say why.
	RuleState_RULE_STATE_BROKEN RuleState = 4
)

// Enum value maps for RuleState.
var (
	RuleState_name = map[int32]string{
		0: "RULE_STATE_UNSPECIFIED",
		1: "RULE_STATE_ACTIVE",
		2: "RULE_STATE_PAUSED",
		3: "RULE_STATE_DELETED",
		4: "RULE_STATE_BROKEN",
	}
	RuleState_value = map[string]int32{
		"RULE_STATE_UNSPECIFIED": 0,
		"RULE_STATE_ACTIVE":      1,
		"RULE_STATE_PAUSED":      2,
		"RULE_STATE_DELETED":     3,
		"RULE_STATE_BROKEN":      4,
	}
)

func (x RuleState) Enum() *RuleState {
	p := new(RuleState)
	*p = x
	return p
}

func (x RuleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleState) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_console_v1_rules_proto_enumTypes[0].Descriptor()
}

func (RuleState) Type() protoreflect.EnumType {
	return &file_backplanepb_console_v1_rules_proto_enumTypes[0]
}

func (x RuleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleState.Descriptor instead.
func (RuleState) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{0}
}

// RuleDefinition is what a rule says: the event, the filter and the steps.
// Its protojson is the canonical form (the console edits it as YAML).
type RuleDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full event name "<service>.<Event>".
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// CEL bool over `event` and `meta`: the rule runs only when true;
	// empty: always.
	When string `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	// By name; order as in BindingDefinition.steps.
	Steps map[string]*Step `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Free text for people; not executed.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The graph editor's layout; ignored by compile and execution.
	Editor        *EditorLayout `protobuf:"bytes,15,opt,name=editor,proto3" json:"editor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDefinition) Reset() {
	*x = RuleDefinition{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDefinition) ProtoMessage() {}

func (x *RuleDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDefinition.ProtoReflect.Descriptor instead.
func (*RuleDefinition) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{0}
}

func (x *RuleDefinition) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *RuleDefinition) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *RuleDefinition) GetSteps() map[string]*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RuleDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleDefinition) GetEditor() *EditorLayout {
	if x != nil {
		return x.Editor
	}
	return nil
}

// RuleVersion is one saved version of a rule.
type RuleVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid of the rule.
	RuleId string `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// Counts from 1 per rule.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Absent on a tombstone.
	Definition *RuleDefinition `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	// A tombstone: the delete of the rule.
	Deleted   bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Author    string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Comment   string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The version this one rolls back to; 0 when it is not a rollback.
	RollbackOf    uint64 `protobuf:"varint,9,opt,name=rollback_of,json=rollbackOf,proto3" json:"rollback_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleVersion) Reset() {
	*x = RuleVersion{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleVersion) ProtoMessage() {}

func (x *RuleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleVersion.ProtoReflect.Descriptor instead.
func (*RuleVersion) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{1}
}

func (x *RuleVersion) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleVersion) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleVersion) GetDefinition() *RuleDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *RuleVersion) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *RuleVersion) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RuleVersion) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RuleVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RuleVersion) GetRollbackOf() uint64 {
	if x != nil {
		return x.RollbackOf
	}
	return 0
}

// Rule is a rule as ListRules shows it.
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// No runs start while paused.
	Paused    bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	Current   *RuleVersion           `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// BROKEN wins over PAUSED: a paused rule that no longer compiles is
	// broken.
	State RuleState `protobuf:"varint,5,opt,name=state,proto3,enum=backplane.console.v1.RuleState" json:"state,omitempty"`
	// Why the current definition does not compile against the latest
	// manifests (state BROKEN); empty otherwise.
	Violations    []*Violation `protobuf:"bytes,6,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Rule) GetCurrent() *RuleVersion {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Rule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Rule) GetState() RuleState {
	if x != nil {
		return x.State
	}
	return RuleState_RULE_STATE_UNSPECIFIED
}

func (x *Rule) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type ListRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only rules of this event ("<service>.<Event>"); empty: all.
	Event         string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{3}
}

func (x *ListRulesRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type ListRulesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// By name, then id.
	Rules         []*Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{4}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type GetRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 0: the current version.
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{5}
}

func (x *GetRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRuleRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rule  *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	// The version asked for.
	Version *RuleVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Why that version does not compile against the latest manifests;
	// empty when it does (or is a tombstone).
	Violations    []*Violation `protobuf:"bytes,3,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleResponse) Reset() {
	*x = GetRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleResponse) ProtoMessage() {}

func (x *GetRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleResponse.ProtoReflect.Descriptor instead.
func (*GetRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{6}
}

func (x *GetRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *GetRuleResponse) GetVersion() *RuleVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetRuleResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type ListRuleVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Versions below this one; 0: from the newest.
	Before uint64 `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	// At most this many (default 50, at most 500).
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleVersionsRequest) Reset() {
	*x = ListRuleVersionsRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleVersionsRequest) ProtoMessage() {}

func (x *ListRuleVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleVersionsRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{7}
}

func (x *ListRuleVersionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRuleVersionsRequest) GetBefore() uint64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *ListRuleVersionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRuleVersionsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Versions []*RuleVersion         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// `before` of the next page; 0 when this is the last one.
	NextBefore    uint64 `protobuf:"varint,2,opt,name=next_before,json=nextBefore,proto3" json:"next_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleVersionsResponse) Reset() {
	*x = ListRuleVersionsResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleVersionsResponse) ProtoMessage() {}

func (x *ListRuleVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListRuleVersionsResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{8}
}

func (x *ListRuleVersionsResponse) GetVersions() []*RuleVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListRuleVersionsResponse) GetNextBefore() uint64 {
	if x != nil {
		return x.NextBefore
	}
	return 0
}

type ValidateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *RuleDefinition        `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleRequest) Reset() {
	*x = ValidateRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleRequest) ProtoMessage() {}

func (x *ValidateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleRequest.ProtoReflect.Descriptor instead.
func (*ValidateRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateRuleRequest) GetDefinition() *RuleDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type ValidateRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty: the definition is valid.
	Violations    []*Violation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleResponse) Reset() {
	*x = ValidateRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleResponse) ProtoMessage() {}

func (x *ValidateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleResponse.ProtoReflect.Descriptor instead.
func (*ValidateRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateRuleResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type SaveRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty: a new rule.
	Id         string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition *RuleDefinition `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Comment    string          `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	// The current version the edit started from. Set: the save is refused
	// with ABORTED when the rule's current version is another one. Unset
	// (and for a new rule): no check.
	BaseVersion   *uint64 `protobuf:"varint,5,opt,name=base_version,json=baseVersion,proto3,oneof" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRuleRequest) Reset() {
	*x = SaveRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRuleRequest) ProtoMessage() {}

func (x *SaveRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRuleRequest.ProtoReflect.Descriptor instead.
func (*SaveRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{11}
}

func (x *SaveRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveRuleRequest) GetDefinition() *RuleDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *SaveRuleRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SaveRuleRequest) GetBaseVersion() uint64 {
	if x != nil && x.BaseVersion != nil {
		return *x.BaseVersion
	}
	return 0
}

type SaveRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The saved version; absent when the definition is rejected.
	Version       *RuleVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Violations    []*Violation `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRuleResponse) Reset() {
	*x = SaveRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRuleResponse) ProtoMessage() {}

func (x *SaveRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRuleResponse.ProtoReflect.Descriptor instead.
func (*SaveRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{12}
}

func (x *SaveRuleResponse) GetVersion() *RuleVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SaveRuleResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type RollbackRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The version whose name and definition become the new version.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	// As SaveRuleRequest.base_version.
	BaseVersion   *uint64 `protobuf:"varint,4,opt,name=base_version,json=baseVersion,proto3,oneof" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRuleRequest) Reset() {
	*x = RollbackRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRuleRequest) ProtoMessage() {}

func (x *RollbackRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRuleRequest.ProtoReflect.Descriptor instead.
func (*RollbackRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RollbackRuleRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackRuleRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RollbackRuleRequest) GetBaseVersion() uint64 {
	if x != nil && x.BaseVersion != nil {
		return *x.BaseVersion
	}
	return 0
}

type RollbackRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *RuleVersion           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Violations    []*Violation           `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRuleResponse) Reset() {
	*x = RollbackRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRuleResponse) ProtoMessage() {}

func (x *RollbackRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRuleResponse.ProtoReflect.Descriptor instead.
func (*RollbackRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{14}
}

func (x *RollbackRuleResponse) GetVersion() *RuleVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RollbackRuleResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type DeleteRuleRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	// As SaveRuleRequest.base_version.
	BaseVersion   *uint64 `protobuf:"varint,3,opt,name=base_version,json=baseVersion,proto3,oneof" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRuleRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *DeleteRuleRequest) GetBaseVersion() uint64 {
	if x != nil && x.BaseVersion != nil {
		return *x.BaseVersion
	}
	return 0
}

type DeleteRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tombstone.
	Version       *RuleVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRuleResponse) GetVersion() *RuleVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type PauseRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// As SaveRuleRequest.base_version: the pause applies to the version the
	// operator saw.
	BaseVersion   *uint64 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3,oneof" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuleRequest) Reset() {
	*x = PauseRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuleRequest) ProtoMessage() {}

func (x *PauseRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuleRequest.ProtoReflect.Descriptor instead.
func (*PauseRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{17}
}

func (x *PauseRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PauseRuleRequest) GetBaseVersion() uint64 {
	if x != nil && x.BaseVersion != nil {
		return *x.BaseVersion
	}
	return 0
}

type PauseRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuleResponse) Reset() {
	*x = PauseRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuleResponse) ProtoMessage() {}

func (x *PauseRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuleResponse.ProtoReflect.Descriptor instead.
func (*PauseRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{18}
}

func (x *PauseRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ResumeRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// As PauseRuleRequest.base_version.
	BaseVersion   *uint64 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3,oneof" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuleRequest) Reset() {
	*x = ResumeRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuleRequest) ProtoMessage() {}

func (x *ResumeRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuleRequest.ProtoReflect.Descriptor instead.
func (*ResumeRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{19}
}

func (x *ResumeRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResumeRuleRequest) GetBaseVersion() uint64 {
	if x != nil && x.BaseVersion != nil {
		return *x.BaseVersion
	}
	return 0
}

type ResumeRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuleResponse) Reset() {
	*x = ResumeRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuleResponse) ProtoMessage() {}

func (x *ResumeRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuleResponse.ProtoReflect.Descriptor instead.
func (*ResumeRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{20}
}

func (x *ResumeRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type WatchRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only rules of this event; empty: all.
	Event         string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRulesRequest) Reset() {
	*x = WatchRulesRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRulesRequest) ProtoMessage() {}

func (x *WatchRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRulesRequest.ProtoReflect.Descriptor instead.
func (*WatchRulesRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{21}
}

func (x *WatchRulesRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type WatchRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRulesResponse) Reset() {
	*x = WatchRulesResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRulesResponse) ProtoMessage() {}

func (x *WatchRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRulesResponse.ProtoReflect.Descriptor instead.
func (*WatchRulesResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{22}
}

func (x *WatchRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// RuleEventMeta are the CloudEvents attributes of a sample event (the CEL
// variable `meta`).
type RuleEventMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ce-id; empty: a new uuid.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ce-source; empty: the event's service.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// ce-subject, the key; empty: none.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// ce-type; empty: the full event name.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// ce-time; unset: now.
	Time          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleEventMeta) Reset() {
	*x = RuleEventMeta{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleEventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEventMeta) ProtoMessage() {}

func (x *RuleEventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEventMeta.ProtoReflect.Descriptor instead.
func (*RuleEventMeta) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{23}
}

func (x *RuleEventMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleEventMeta) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleEventMeta) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RuleEventMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuleEventMeta) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TestRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The saved rule (uuid); exclusive with definition.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Version of the saved rule; 0: the current one.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// An unsaved definition; exclusive with id.
	Definition *RuleDefinition `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	// The event's payload: JSON text; empty is {}.
	Event string         `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	Meta  *RuleEventMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	// Only evaluate `when`: no run starts.
	DryRun bool `protobuf:"varint,6,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// How long to wait for the run; zero: 30s, at most 10 minutes.
	Timeout       *durationpb.Duration `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleRequest) Reset() {
	*x = TestRuleRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleRequest) ProtoMessage() {}

func (x *TestRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleRequest.ProtoReflect.Descriptor instead.
func (*TestRuleRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{24}
}

func (x *TestRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestRuleRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestRuleRequest) GetDefinition() *RuleDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *TestRuleRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TestRuleRequest) GetMeta() *RuleEventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TestRuleRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *TestRuleRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type TestRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Violations of the definition; when present nothing was evaluated.
	Violations []*Violation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	// The event matched `when` (a rule without when always matches).
	Matched bool `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	// The event or `when` failed to evaluate ("transform failed at when:
	// ..."); matched is false then.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// The attributes the event was evaluated with (defaults filled in).
	Meta *RuleEventMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	// The test run's end; absent when not matched or dry_run.
	Result        *CallResult `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleResponse) Reset() {
	*x = TestRuleResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleResponse) ProtoMessage() {}

func (x *TestRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleResponse.ProtoReflect.Descriptor instead.
func (*TestRuleResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{25}
}

func (x *TestRuleResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *TestRuleResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *TestRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestRuleResponse) GetMeta() *RuleEventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TestRuleResponse) GetResult() *CallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListRuleRunsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Only this status.
	Status RunStatus `protobuf:"varint,2,opt,name=status,proto3,enum=backplane.console.v1.RunStatus" json:"status,omitempty"`
	// Test runs (test/rule/<id>/) instead of the event runs (rule/<id>/).
	Tests bool `protobuf:"varint,3,opt,name=tests,proto3" json:"tests,omitempty"`
	// At most this many (default 50, at most 500).
	PageSize uint32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// From the previous response; empty: the first page.
	PageToken     []byte `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleRunsRequest) Reset() {
	*x = ListRuleRunsRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleRunsRequest) ProtoMessage() {}

func (x *ListRuleRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleRunsRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{26}
}

func (x *ListRuleRunsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRuleRunsRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *ListRuleRunsRequest) GetTests() bool {
	if x != nil {
		return x.Tests
	}
	return false
}

func (x *ListRuleRunsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRuleRunsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

type ListRuleRunsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Runs  []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	// Empty on the last page.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The visibility query that was run.
	Query         string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleRunsResponse) Reset() {
	*x = ListRuleRunsResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleRunsResponse) ProtoMessage() {}

func (x *ListRuleRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRuleRunsResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{27}
}

func (x *ListRuleRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRuleRunsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

func (x *ListRuleRunsResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetRuleRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rule; empty for a test run of an unsaved definition
	// (test/rule/draft/...).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A run of the rule: rule/<id>/... or test/rule/<id>/...
	WorkflowId string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Empty: the latest run.
	RunId         string `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRunRequest) Reset() {
	*x = GetRuleRunRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRunRequest) ProtoMessage() {}

func (x *GetRuleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRunRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRunRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{28}
}

func (x *GetRuleRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRuleRunRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetRuleRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRuleRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Run   *GetRunResponse        `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	// The version that ran (0: an unsaved definition) and whether it is a
	// test run.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Test    bool   `protobuf:"varint,3,opt,name=test,proto3" json:"test,omitempty"`
	// The program's steps by name, then every compensation in
	// the order it was scheduled.
	Steps         []*StepRun `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRunResponse) Reset() {
	*x = GetRuleRunResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRunResponse) ProtoMessage() {}

func (x *GetRuleRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRunResponse.ProtoReflect.Descriptor instead.
func (*GetRuleRunResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{29}
}

func (x *GetRuleRunResponse) GetRun() *GetRunResponse {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *GetRuleRunResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetRuleRunResponse) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

func (x *GetRuleRunResponse) GetSteps() []*StepRun {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CancelRuleRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// As GetRuleRunRequest.id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A run of the rule: rule/<id>/... or test/rule/<id>/...
	WorkflowId    string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRuleRunRequest) Reset() {
	*x = CancelRuleRunRequest{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRuleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRuleRunRequest) ProtoMessage() {}

func (x *CancelRuleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRuleRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRuleRunRequest) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{30}
}

func (x *CancelRuleRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelRuleRunRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CancelRuleRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRuleRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRuleRunResponse) Reset() {
	*x = CancelRuleRunResponse{}
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRuleRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRuleRunResponse) ProtoMessage() {}

func (x *CancelRuleRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_console_v1_rules_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRuleRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRuleRunResponse) Descriptor() ([]byte, []int) {
	return file_backplanepb_console_v1_rules_proto_rawDescGZIP(), []int{31}
}

var File_backplanepb_console_v1_rules_proto protoreflect.FileDescriptor

const file_backplanepb_console_v1_rules_proto_rawDesc = "" +
	"\n" +
	"\"backplanepb/console/v1/rules.proto\x12\x14backplane.console.v1\x1a\"backplanepb/console/v1/calls.proto\x1a!backplanepb/console/v1/step.proto\x1a&backplanepb/console/v1/workflows.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n" +
	"\x0eRuleDefinition\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04when\x18\x02 \x01(\tR\x04when\x12E\n" +
	"\x05steps\x18\x03 \x03(\v2/.backplane.console.v1.RuleDefinition.StepsEntryR\x05steps\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12:\n" +
	"\x06editor\x18\x0f \x01(\v2\".backplane.console.v1.EditorLayoutR\x06editor\x1aT\n" +
	"\n" +
	"StepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.backplane.console.v1.StepR\x05value:\x028\x01\"\xc2\x02\n" +
	"\vRuleVersion\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12D\n" +
	"\n" +
	"definition\x18\x04 \x01(\v2$.backplane.console.v1.RuleDefinitionR\n" +
	"definition\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vrollback_of\x18\t \x01(\x04R\n" +
	"rollbackOf\"\x9e\x02\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\x12;\n" +
	"\acurrent\x18\x03 \x01(\v2!.backplane.console.v1.RuleVersionR\acurrent\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1f.backplane.console.v1.RuleStateR\x05state\x12?\n" +
	"\n" +
	"violations\x18\x06 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\"(\n" +
	"\x10ListRulesRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\"E\n" +
	"\x11ListRulesResponse\x120\n" +
	"\x05rules\x18\x01 \x03(\v2\x1a.backplane.console.v1.RuleR\x05rules\":\n" +
	"\x0eGetRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xbf\x01\n" +
	"\x0fGetRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.backplane.console.v1.RuleR\x04rule\x12;\n" +
	"\aversion\x18\x02 \x01(\v2!.backplane.console.v1.RuleVersionR\aversion\x12?\n" +
	"\n" +
	"violations\x18\x03 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\"^\n" +
	"\x17ListRuleVersionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06before\x18\x02 \x01(\x04R\x06before\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"z\n" +
	"\x18ListRuleVersionsResponse\x12=\n" +
	"\bversions\x18\x01 \x03(\v2!.backplane.console.v1.RuleVersionR\bversions\x12\x1f\n" +
	"\vnext_before\x18\x02 \x01(\x04R\n" +
	"nextBefore\"[\n" +
	"\x13ValidateRuleRequest\x12D\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2$.backplane.console.v1.RuleDefinitionR\n" +
	"definition\"W\n" +
	"\x14ValidateRuleResponse\x12?\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\"\xce\x01\n" +
	"\x0fSaveRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12D\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2$.backplane.console.v1.RuleDefinitionR\n" +
	"definition\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12&\n" +
	"\fbase_version\x18\x05 \x01(\x04H\x00R\vbaseVersion\x88\x01\x01B\x0f\n" +
	"\r_base_version\"\x90\x01\n" +
	"\x10SaveRuleResponse\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.backplane.console.v1.RuleVersionR\aversion\x12?\n" +
	"\n" +
	"violations\x18\x02 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\"\x92\x01\n" +
	"\x13RollbackRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12&\n" +
	"\fbase_version\x18\x04 \x01(\x04H\x00R\vbaseVersion\x88\x01\x01B\x0f\n" +
	"\r_base_version\"\x94\x01\n" +
	"\x14RollbackRuleResponse\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.backplane.console.v1.RuleVersionR\aversion\x12?\n" +
	"\n" +
	"violations\x18\x02 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\"v\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12&\n" +
	"\fbase_version\x18\x03 \x01(\x04H\x00R\vbaseVersion\x88\x01\x01B\x0f\n" +
	"\r_base_version\"Q\n" +
	"\x12DeleteRuleResponse\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.backplane.console.v1.RuleVersionR\aversion\"[\n" +
	"\x10PauseRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\fbase_version\x18\x02 \x01(\x04H\x00R\vbaseVersion\x88\x01\x01B\x0f\n" +
	"\r_base_version\"C\n" +
	"\x11PauseRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.backplane.console.v1.RuleR\x04rule\"\\\n" +
	"\x11ResumeRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\fbase_version\x18\x02 \x01(\x04H\x00R\vbaseVersion\x88\x01\x01B\x0f\n" +
	"\r_base_version\"D\n" +
	"\x12ResumeRuleResponse\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.backplane.console.v1.RuleR\x04rule\")\n" +
	"\x11WatchRulesRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\"F\n" +
	"\x12WatchRulesResponse\x120\n" +
	"\x05rules\x18\x01 \x03(\v2\x1a.backplane.console.v1.RuleR\x05rules\"\x95\x01\n" +
	"\rRuleEventMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x9e\x02\n" +
	"\x0fTestRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12D\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2$.backplane.console.v1.RuleDefinitionR\n" +
	"definition\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x127\n" +
	"\x04meta\x18\x05 \x01(\v2#.backplane.console.v1.RuleEventMetaR\x04meta\x12\x17\n" +
	"\adry_run\x18\x06 \x01(\bR\x06dryRun\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xf6\x01\n" +
	"\x10TestRuleResponse\x12?\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2\x1f.backplane.console.v1.ViolationR\n" +
	"violations\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x127\n" +
	"\x04meta\x18\x04 \x01(\v2#.backplane.console.v1.RuleEventMetaR\x04meta\x128\n" +
	"\x06result\x18\x05 \x01(\v2 .backplane.console.v1.CallResultR\x06result\"\xb0\x01\n" +
	"\x13ListRuleRunsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.backplane.console.v1.RunStatusR\x06status\x12\x14\n" +
	"\x05tests\x18\x03 \x01(\bR\x05tests\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\fR\tpageToken\"\x83\x01\n" +
	"\x14ListRuleRunsResponse\x12-\n" +
	"\x04runs\x18\x01 \x03(\v2\x19.backplane.console.v1.RunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fR\rnextPageToken\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"[\n" +
	"\x11GetRuleRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\xaf\x01\n" +
	"\x12GetRuleRunResponse\x126\n" +
	"\x03run\x18\x01 \x01(\v2$.backplane.console.v1.GetRunResponseR\x03run\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04test\x18\x03 \x01(\bR\x04test\x123\n" +
	"\x05steps\x18\x04 \x03(\v2\x1d.backplane.console.v1.StepRunR\x05steps\"^\n" +
	"\x14CancelRuleRunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\x17\n" +
	"\x15CancelRuleRunResponse*\x84\x01\n" +
	"\tRuleState\x12\x1a\n" +
	"\x16RULE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RULE_STATE_ACTIVE\x10\x01\x12\x15\n" +
	"\x11RULE_STATE_PAUSED\x10\x02\x12\x16\n" +
	"\x12RULE_STATE_DELETED\x10\x03\x12\x15\n" +
	"\x11RULE_STATE_BROKEN\x10\x042\xef\n" +
	"\n" +
	"\vRuleService\x12\\\n" +
	"\tListRules\x12&.backplane.console.v1.ListRulesRequest\x1a'.backplane.console.v1.ListRulesResponse\x12V\n" +
	"\aGetRule\x12$.backplane.console.v1.GetRuleRequest\x1a%.backplane.console.v1.GetRuleResponse\x12q\n" +
	"\x10ListRuleVersions\x12-.backplane.console.v1.ListRuleVersionsRequest\x1a..backplane.console.v1.ListRuleVersionsResponse\x12e\n" +
	"\fValidateRule\x12).backplane.console.v1.ValidateRuleRequest\x1a*.backplane.console.v1.ValidateRuleResponse\x12Y\n" +
	"\bSaveRule\x12%.backplane.console.v1.SaveRuleRequest\x1a&.backplane.console.v1.SaveRuleResponse\x12e\n" +
	"\fRollbackRule\x12).backplane.console.v1.RollbackRuleRequest\x1a*.backplane.console.v1.RollbackRuleResponse\x12_\n" +
	"\n" +
	"DeleteRule\x12'.backplane.console.v1.DeleteRuleRequest\x1a(.backplane.console.v1.DeleteRuleResponse\x12\\\n" +
	"\tPauseRule\x12&.backplane.console.v1.PauseRuleRequest\x1a'.backplane.console.v1.PauseRuleResponse\x12_\n" +
	"\n" +
	"ResumeRule\x12'.backplane.console.v1.ResumeRuleRequest\x1a(.backplane.console.v1.ResumeRuleResponse\x12a\n" +
	"\n" +
	"WatchRules\x12'.backplane.console.v1.WatchRulesRequest\x1a(.backplane.console.v1.WatchRulesResponse0\x01\x12Y\n" +
	"\bTestRule\x12%.backplane.console.v1.TestRuleRequest\x1a&.backplane.console.v1.TestRuleResponse\x12e\n" +
	"\fListRuleRuns\x12).backplane.console.v1.ListRuleRunsRequest\x1a*.backplane.console.v1.ListRuleRunsResponse\x12_\n" +
	"\n" +
	"GetRuleRun\x12'.backplane.console.v1.GetRuleRunRequest\x1a(.backplane.console.v1.GetRuleRunResponse\x12h\n" +
	"\rCancelRuleRun\x12*.backplane.console.v1.CancelRuleRunRequest\x1a+.backplane.console.v1.CancelRuleRunResponseB@Z>github.com/gopherex/backplane/backplanepb/console/v1;consolev1b\x06proto3"

var (
	file_backplanepb_console_v1_rules_proto_rawDescOnce sync.Once
	file_backplanepb_console_v1_rules_proto_rawDescData []byte
)

func file_backplanepb_console_v1_rules_proto_rawDescGZIP() []byte {
	file_backplanepb_console_v1_rules_proto_rawDescOnce.Do(func() {
		file_backplanepb_console_v1_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_rules_proto_rawDesc), len(file_backplanepb_console_v1_rules_proto_rawDesc)))
	})
	return file_backplanepb_console_v1_rules_proto_rawDescData
}

var file_backplanepb_console_v1_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backplanepb_console_v1_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_backplanepb_console_v1_rules_proto_goTypes = []any{
	(RuleState)(0),                   // 0: backplane.console.v1.RuleState
	(*RuleDefinition)(nil),           // 1: backplane.console.v1.RuleDefinition
	(*RuleVersion)(nil),              // 2: backplane.console.v1.RuleVersion
	(*Rule)(nil),                     // 3: backplane.console.v1.Rule
	(*ListRulesRequest)(nil),         // 4: backplane.console.v1.ListRulesRequest
	(*ListRulesResponse)(nil),        // 5: backplane.console.v1.ListRulesResponse
	(*GetRuleRequest)(nil),           // 6: backplane.console.v1.GetRuleRequest
	(*GetRuleResponse)(nil),          // 7: backplane.console.v1.GetRuleResponse
	(*ListRuleVersionsRequest)(nil),  // 8: backplane.console.v1.ListRuleVersionsRequest
	(*ListRuleVersionsResponse)(nil), // 9: backplane.console.v1.ListRuleVersionsResponse
	(*ValidateRuleRequest)(nil),      // 10: backplane.console.v1.ValidateRuleRequest
	(*ValidateRuleResponse)(nil),     // 11: backplane.console.v1.ValidateRuleResponse
	(*SaveRuleRequest)(nil),          // 12: backplane.console.v1.SaveRuleRequest
	(*SaveRuleResponse)(nil),         // 13: backplane.console.v1.SaveRuleResponse
	(*RollbackRuleRequest)(nil),      // 14: backplane.console.v1.RollbackRuleRequest
	(*RollbackRuleResponse)(nil),     // 15: backplane.console.v1.RollbackRuleResponse
	(*DeleteRuleRequest)(nil),        // 16: backplane.console.v1.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),       // 17: backplane.console.v1.DeleteRuleResponse
	(*PauseRuleRequest)(nil),         // 18: backplane.console.v1.PauseRuleRequest
	(*PauseRuleResponse)(nil),        // 19: backplane.console.v1.PauseRuleResponse
	(*ResumeRuleRequest)(nil),        // 20: backplane.console.v1.ResumeRuleRequest
	(*ResumeRuleResponse)(nil),       // 21: backplane.console.v1.ResumeRuleResponse
	(*WatchRulesRequest)(nil),        // 22: backplane.console.v1.WatchRulesRequest
	(*WatchRulesResponse)(nil),       // 23: backplane.console.v1.WatchRulesResponse
	(*RuleEventMeta)(nil),            // 24: backplane.console.v1.RuleEventMeta
	(*TestRuleRequest)(nil),          // 25: backplane.console.v1.TestRuleRequest
	(*TestRuleResponse)(nil),         // 26: backplane.console.v1.TestRuleResponse
	(*ListRuleRunsRequest)(nil),      // 27: backplane.console.v1.ListRuleRunsRequest
	(*ListRuleRunsResponse)(nil),     // 28: backplane.console.v1.ListRuleRunsResponse
	(*GetRuleRunRequest)(nil),        // 29: backplane.console.v1.GetRuleRunRequest
	(*GetRuleRunResponse)(nil),       // 30: backplane.console.v1.GetRuleRunResponse
	(*CancelRuleRunRequest)(nil),     // 31: backplane.console.v1.CancelRuleRunRequest
	(*CancelRuleRunResponse)(nil),    // 32: backplane.console.v1.CancelRuleRunResponse
	nil,                              // 33: backplane.console.v1.RuleDefinition.StepsEntry
	(*EditorLayout)(nil),             // 34: backplane.console.v1.EditorLayout
	(*timestamppb.Timestamp)(nil),    // 35: google.protobuf.Timestamp
	(*Violation)(nil),                // 36: backplane.console.v1.Violation
	(*durationpb.Duration)(nil),      // 37: google.protobuf.Duration
	(*CallResult)(nil),               // 38: backplane.console.v1.CallResult
	(RunStatus)(0),                   // 39: backplane.console.v1.RunStatus
	(*Run)(nil),                      // 40: backplane.console.v1.Run
	(*GetRunResponse)(nil),           // 41: backplane.console.v1.GetRunResponse
	(*StepRun)(nil),                  // 42: backplane.console.v1.StepRun
	(*Step)(nil),                     // 43: backplane.console.v1.Step
}
var file_backplanepb_console_v1_rules_proto_depIdxs = []int32{
	33, // 0: backplane.console.v1.RuleDefinition.steps:type_name -> backplane.console.v1.RuleDefinition.StepsEntry
	34, // 1: backplane.console.v1.RuleDefinition.editor:type_name -> backplane.console.v1.EditorLayout
	1,  // 2: backplane.console.v1.RuleVersion.definition:type_name -> backplane.console.v1.RuleDefinition
	35, // 3: backplane.console.v1.RuleVersion.created_at:type_name -> google.protobuf.Timestamp
	2,  // 4: backplane.console.v1.Rule.current:type_name -> backplane.console.v1.RuleVersion
	35, // 5: backplane.console.v1.Rule.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: backplane.console.v1.Rule.state:type_name -> backplane.console.v1.RuleState
	36, // 7: backplane.console.v1.Rule.violations:type_name -> backplane.console.v1.Violation
	3,  // 8: backplane.console.v1.ListRulesResponse.rules:type_name -> backplane.console.v1.Rule
	3,  // 9: backplane.console.v1.GetRuleResponse.rule:type_name -> backplane.console.v1.Rule
	2,  // 10: backplane.console.v1.GetRuleResponse.version:type_name -> backplane.console.v1.RuleVersion
	36, // 11: backplane.console.v1.GetRuleResponse.violations:type_name -> backplane.console.v1.Violation
	2,  // 12: backplane.console.v1.ListRuleVersionsResponse.versions:type_name -> backplane.console.v1.RuleVersion
	1,  // 13: backplane.console.v1.ValidateRuleRequest.definition:type_name -> backplane.console.v1.RuleDefinition
	36, // 14: backplane.console.v1.ValidateRuleResponse.violations:type_name -> backplane.console.v1.Violation
	1,  // 15: backplane.console.v1.SaveRuleRequest.definition:type_name -> backplane.console.v1.RuleDefinition
	2,  // 16: backplane.console.v1.SaveRuleResponse.version:type_name -> backplane.console.v1.RuleVersion
	36, // 17: backplane.console.v1.SaveRuleResponse.violations:type_name -> backplane.console.v1.Violation
	2,  // 18: backplane.console.v1.RollbackRuleResponse.version:type_name -> backplane.console.v1.RuleVersion
	36, // 19: backplane.console.v1.RollbackRuleResponse.violations:type_name -> backplane.console.v1.Violation
	2,  // 20: backplane.console.v1.DeleteRuleResponse.version:type_name -> backplane.console.v1.RuleVersion
	3,  // 21: backplane.console.v1.PauseRuleResponse.rule:type_name -> backplane.console.v1.Rule
	3,  // 22: backplane.console.v1.ResumeRuleResponse.rule:type_name -> backplane.console.v1.Rule
	3,  // 23: backplane.console.v1.WatchRulesResponse.rules:type_name -> backplane.console.v1.Rule
	35, // 24: backplane.console.v1.RuleEventMeta.time:type_name -> google.protobuf.Timestamp
	1,  // 25: backplane.console.v1.TestRuleRequest.definition:type_name -> backplane.console.v1.RuleDefinition
	24, // 26: backplane.console.v1.TestRuleRequest.meta:type_name -> backplane.console.v1.RuleEventMeta
	37, // 27: backplane.console.v1.TestRuleRequest.timeout:type_name -> google.protobuf.Duration
	36, // 28: backplane.console.v1.TestRuleResponse.violations:type_name -> backplane.console.v1.Violation
	24, // 29: backplane.console.v1.TestRuleResponse.meta:type_name -> backplane.console.v1.RuleEventMeta
	38, // 30: backplane.console.v1.TestRuleResponse.result:type_name -> backplane.console.v1.CallResult
	39, // 31: backplane.console.v1.ListRuleRunsRequest.status:type_name -> backplane.console.v1.RunStatus
	40, // 32: backplane.console.v1.ListRuleRunsResponse.runs:type_name -> backplane.console.v1.Run
	41, // 33: backplane.console.v1.GetRuleRunResponse.run:type_name -> backplane.console.v1.GetRunResponse
	42, // 34: backplane.console.v1.GetRuleRunResponse.steps:type_name -> backplane.console.v1.StepRun
	43, // 35: backplane.console.v1.RuleDefinition.StepsEntry.value:type_name -> backplane.console.v1.Step
	4,  // 36: backplane.console.v1.RuleService.ListRules:input_type -> backplane.console.v1.ListRulesRequest
	6,  // 37: backplane.console.v1.RuleService.GetRule:input_type -> backplane.console.v1.GetRuleRequest
	8,  // 38: backplane.console.v1.RuleService.ListRuleVersions:input_type -> backplane.console.v1.ListRuleVersionsRequest
	10, // 39: backplane.console.v1.RuleService.ValidateRule:input_type -> backplane.console.v1.ValidateRuleRequest
	12, // 40: backplane.console.v1.RuleService.SaveRule:input_type -> backplane.console.v1.SaveRuleRequest
	14, // 41: backplane.console.v1.RuleService.RollbackRule:input_type -> backplane.console.v1.RollbackRuleRequest
	16, // 42: backplane.console.v1.RuleService.DeleteRule:input_type -> backplane.console.v1.DeleteRuleRequest
	18, // 43: backplane.console.v1.RuleService.PauseRule:input_type -> backplane.console.v1.PauseRuleRequest
	20, // 44: backplane.console.v1.RuleService.ResumeRule:input_type -> backplane.console.v1.ResumeRuleRequest
	22, // 45: backplane.console.v1.RuleService.WatchRules:input_type -> backplane.console.v1.WatchRulesRequest
	25, // 46: backplane.console.v1.RuleService.TestRule:input_type -> backplane.console.v1.TestRuleRequest
	27, // 47: backplane.console.v1.RuleService.ListRuleRuns:input_type -> backplane.console.v1.ListRuleRunsRequest
	29, // 48: backplane.console.v1.RuleService.GetRuleRun:input_type -> backplane.console.v1.GetRuleRunRequest
	31, // 49: backplane.console.v1.RuleService.CancelRuleRun:input_type -> backplane.console.v1.CancelRuleRunRequest
	5,  // 50: backplane.console.v1.RuleService.ListRules:output_type -> backplane.console.v1.ListRulesResponse
	7,  // 51: backplane.console.v1.RuleService.GetRule:output_type -> backplane.console.v1.GetRuleResponse
	9,  // 52: backplane.console.v1.RuleService.ListRuleVersions:output_type -> backplane.console.v1.ListRuleVersionsResponse
	11, // 53: backplane.console.v1.RuleService.ValidateRule:output_type -> backplane.console.v1.ValidateRuleResponse
	13, // 54: backplane.console.v1.RuleService.SaveRule:output_type -> backplane.console.v1.SaveRuleResponse
	15, // 55: backplane.console.v1.RuleService.RollbackRule:output_type -> backplane.console.v1.RollbackRuleResponse
	17, // 56: backplane.console.v1.RuleService.DeleteRule:output_type -> backplane.console.v1.DeleteRuleResponse
	19, // 57: backplane.console.v1.RuleService.PauseRule:output_type -> backplane.console.v1.PauseRuleResponse
	21, // 58: backplane.console.v1.RuleService.ResumeRule:output_type -> backplane.console.v1.ResumeRuleResponse
	23, // 59: backplane.console.v1.RuleService.WatchRules:output_type -> backplane.console.v1.WatchRulesResponse
	26, // 60: backplane.console.v1.RuleService.TestRule:output_type -> backplane.console.v1.TestRuleResponse
	28, // 61: backplane.console.v1.RuleService.ListRuleRuns:output_type -> backplane.console.v1.ListRuleRunsResponse
	30, // 62: backplane.console.v1.RuleService.GetRuleRun:output_type -> backplane.console.v1.GetRuleRunResponse
	32, // 63: backplane.console.v1.RuleService.CancelRuleRun:output_type -> backplane.console.v1.CancelRuleRunResponse
	50, // [50:64] is the sub-list for method output_type
	36, // [36:50] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_backplanepb_console_v1_rules_proto_init() }
func file_backplanepb_console_v1_rules_proto_init() {
	if File_backplanepb_console_v1_rules_proto != nil {
		return
	}
	file_backplanepb_console_v1_calls_proto_init()
	file_backplanepb_console_v1_step_proto_init()
	file_backplanepb_console_v1_workflows_proto_init()
	file_backplanepb_console_v1_rules_proto_msgTypes[11].OneofWrappers = []any{}
	file_backplanepb_console_v1_rules_proto_msgTypes[13].OneofWrappers = []any{}
	file_backplanepb_console_v1_rules_proto_msgTypes[15].OneofWrappers = []any{}
	file_backplanepb_console_v1_rules_proto_msgTypes[17].OneofWrappers = []any{}
	file_backplanepb_console_v1_rules_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backplanepb_console_v1_rules_proto_rawDesc), len(file_backplanepb_console_v1_rules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backplanepb_console_v1_rules_proto_goTypes,
		DependencyIndexes: file_backplanepb_console_v1_rules_proto_depIdxs,
		EnumInfos:         file_backplanepb_console_v1_rules_proto_enumTypes,
		MessageInfos:      file_backplanepb_console_v1_rules_proto_msgTypes,
	}.Build()
	File_backplanepb_console_v1_rules_proto = out.File
	file_backplanepb_console_v1_rules_proto_goTypes = nil
	file_backplanepb_console_v1_rules_proto_depIdxs = nil
}
