// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/wiring.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WiringService_GetWiringCatalog_FullMethodName = "/backplane.console.v1.WiringService/GetWiringCatalog"
	WiringService_AnalyzeBinding_FullMethodName   = "/backplane.console.v1.WiringService/AnalyzeBinding"
	WiringService_AnalyzeRule_FullMethodName      = "/backplane.console.v1.WiringService/AnalyzeRule"
	WiringService_RenameStep_FullMethodName       = "/backplane.console.v1.WiringService/RenameStep"
)

// WiringServiceClient is the client API for WiringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WiringService is what the console's wiring editor needs besides
// BindingService and RuleService: the contracts there are to wire, the
// analysis of a definition (saved or a draft) for the graph and the
// editor's hints, and refactoring. Nothing here saves.
type WiringServiceClient interface {
	// GetWiringCatalog is every service's hooks, activities and events from
	// its latest manifest: the editor's palette and the types of its ports.
	GetWiringCatalog(ctx context.Context, in *GetWiringCatalogRequest, opts ...grpc.CallOption) (*GetWiringCatalogResponse, error)
	// AnalyzeBinding validates a binding against the latest manifests and
	// describes it: the steps' levels and dependencies, the type of every
	// value and what every expression reads.
	AnalyzeBinding(ctx context.Context, in *AnalyzeBindingRequest, opts ...grpc.CallOption) (*AnalyzeBindingResponse, error)
	// AnalyzeRule is AnalyzeBinding for a rule.
	AnalyzeRule(ctx context.Context, in *AnalyzeRuleRequest, opts ...grpc.CallOption) (*AnalyzeRuleResponse, error)
	// RenameStep renames a step in a definition: its key, every `after`
	// naming it and every expression reading it (by the expressions'
	// syntax trees, so a string or a field of the same name is untouched).
	RenameStep(ctx context.Context, in *RenameStepRequest, opts ...grpc.CallOption) (*RenameStepResponse, error)
}

type wiringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWiringServiceClient(cc grpc.ClientConnInterface) WiringServiceClient {
	return &wiringServiceClient{cc}
}

func (c *wiringServiceClient) GetWiringCatalog(ctx context.Context, in *GetWiringCatalogRequest, opts ...grpc.CallOption) (*GetWiringCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWiringCatalogResponse)
	err := c.cc.Invoke(ctx, WiringService_GetWiringCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiringServiceClient) AnalyzeBinding(ctx context.Context, in *AnalyzeBindingRequest, opts ...grpc.CallOption) (*AnalyzeBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeBindingResponse)
	err := c.cc.Invoke(ctx, WiringService_AnalyzeBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiringServiceClient) AnalyzeRule(ctx context.Context, in *AnalyzeRuleRequest, opts ...grpc.CallOption) (*AnalyzeRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeRuleResponse)
	err := c.cc.Invoke(ctx, WiringService_AnalyzeRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiringServiceClient) RenameStep(ctx context.Context, in *RenameStepRequest, opts ...grpc.CallOption) (*RenameStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameStepResponse)
	err := c.cc.Invoke(ctx, WiringService_RenameStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WiringServiceServer is the server API for WiringService service.
// All implementations must embed UnimplementedWiringServiceServer
// for forward compatibility.
//
// WiringService is what the console's wiring editor needs besides
// BindingService and RuleService: the contracts there are to wire, the
// analysis of a definition (saved or a draft) for the graph and the
// editor's hints, and refactoring. Nothing here saves.
type WiringServiceServer interface {
	// GetWiringCatalog is every service's hooks, activities and events from
	// its latest manifest: the editor's palette and the types of its ports.
	GetWiringCatalog(context.Context, *GetWiringCatalogRequest) (*GetWiringCatalogResponse, error)
	// AnalyzeBinding validates a binding against the latest manifests and
	// describes it: the steps' levels and dependencies, the type of every
	// value and what every expression reads.
	AnalyzeBinding(context.Context, *AnalyzeBindingRequest) (*AnalyzeBindingResponse, error)
	// AnalyzeRule is AnalyzeBinding for a rule.
	AnalyzeRule(context.Context, *AnalyzeRuleRequest) (*AnalyzeRuleResponse, error)
	// RenameStep renames a step in a definition: its key, every `after`
	// naming it and every expression reading it (by the expressions'
	// syntax trees, so a string or a field of the same name is untouched).
	RenameStep(context.Context, *RenameStepRequest) (*RenameStepResponse, error)
	mustEmbedUnimplementedWiringServiceServer()
}

// UnimplementedWiringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWiringServiceServer struct{}

func (UnimplementedWiringServiceServer) GetWiringCatalog(context.Context, *GetWiringCatalogRequest) (*GetWiringCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWiringCatalog not implemented")
}
func (UnimplementedWiringServiceServer) AnalyzeBinding(context.Context, *AnalyzeBindingRequest) (*AnalyzeBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeBinding not implemented")
}
func (UnimplementedWiringServiceServer) AnalyzeRule(context.Context, *AnalyzeRuleRequest) (*AnalyzeRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeRule not implemented")
}
func (UnimplementedWiringServiceServer) RenameStep(context.Context, *RenameStepRequest) (*RenameStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameStep not implemented")
}
func (UnimplementedWiringServiceServer) mustEmbedUnimplementedWiringServiceServer() {}
func (UnimplementedWiringServiceServer) testEmbeddedByValue()                       {}

// UnsafeWiringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WiringServiceServer will
// result in compilation errors.
type UnsafeWiringServiceServer interface {
	mustEmbedUnimplementedWiringServiceServer()
}

func RegisterWiringServiceServer(s grpc.ServiceRegistrar, srv WiringServiceServer) {
	// If the following call panics, it indicates UnimplementedWiringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WiringService_ServiceDesc, srv)
}

func _WiringService_GetWiringCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWiringCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiringServiceServer).GetWiringCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiringService_GetWiringCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiringServiceServer).GetWiringCatalog(ctx, req.(*GetWiringCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiringService_AnalyzeBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiringServiceServer).AnalyzeBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiringService_AnalyzeBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiringServiceServer).AnalyzeBinding(ctx, req.(*AnalyzeBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiringService_AnalyzeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiringServiceServer).AnalyzeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiringService_AnalyzeRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiringServiceServer).AnalyzeRule(ctx, req.(*AnalyzeRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiringService_RenameStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiringServiceServer).RenameStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiringService_RenameStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiringServiceServer).RenameStep(ctx, req.(*RenameStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WiringService_ServiceDesc is the grpc.ServiceDesc for WiringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WiringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.WiringService",
	HandlerType: (*WiringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWiringCatalog",
			Handler:    _WiringService_GetWiringCatalog_Handler,
		},
		{
			MethodName: "AnalyzeBinding",
			Handler:    _WiringService_AnalyzeBinding_Handler,
		},
		{
			MethodName: "AnalyzeRule",
			Handler:    _WiringService_AnalyzeRule_Handler,
		},
		{
			MethodName: "RenameStep",
			Handler:    _WiringService_RenameStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backplanepb/console/v1/wiring.proto",
}
