// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/console/v1/workflows.proto

package consolev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_ListWorkflows_FullMethodName = "/backplane.console.v1.WorkflowService/ListWorkflows"
	WorkflowService_StartWorkflow_FullMethodName = "/backplane.console.v1.WorkflowService/StartWorkflow"
	WorkflowService_ListRuns_FullMethodName      = "/backplane.console.v1.WorkflowService/ListRuns"
	WorkflowService_GetRun_FullMethodName        = "/backplane.console.v1.WorkflowService/GetRun"
	WorkflowService_CancelRun_FullMethodName     = "/backplane.console.v1.WorkflowService/CancelRun"
	WorkflowService_TerminateRun_FullMethodName  = "/backplane.console.v1.WorkflowService/TerminateRun"
	WorkflowService_SignalRun_FullMethodName     = "/backplane.console.v1.WorkflowService/SignalRun"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkflowService is the console's view of the services' Temporal
// workflows (§9): what they declare, starting one with a form, the runs
// through Temporal visibility and the actions on a run. backplane reaches
// Temporal through its own client (BACKPLANE_TEMPORAL_ADDR); without one
// the Temporal-backed calls fail with UNAVAILABLE. Runs the console starts
// carry memo source = console:<session> (§14).
//
// GetRun, CancelRun, TerminateRun and SignalRun address any workflow id of
// backplane's namespace, not only runs on a service's queue: binding and
// rule runs live on backplane's own queue, and the console session is an
// installation operator.
type WorkflowServiceClient interface {
	// Workflows the latest manifests declare: workflows[] and activities
	// of kind WORKFLOW, with the workers polling their task queue.
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	// Starts a declared workflow on the service's task queue. A workflow_id
	// that has a running run is ALREADY_EXISTS; a closed one starts a new run.
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
	// Runs on a service's task queue (or its hook calls), newest start first
	// where the visibility store sorts (Elasticsearch). SQL visibility (the
	// dev server, PostgreSQL, MySQL) refuses ORDER BY; there the order is
	// Temporal's own: running runs first, then by close time, newest first.
	// ListRunsResponse.query shows which query ran.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	// One run: status, input, result or failure, pending activities and
	// its history as a timeline.
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	// Requests cancellation: the workflow sees it and may clean up.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
	// Ends the run at once, without the workflow's code.
	TerminateRun(ctx context.Context, in *TerminateRunRequest, opts ...grpc.CallOption) (*TerminateRunResponse, error)
	// Sends a signal with a JSON argument, or none.
	SignalRun(ctx context.Context, in *SignalRunRequest, opts ...grpc.CallOption) (*SignalRunResponse, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowService_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) TerminateRun(ctx context.Context, in *TerminateRunRequest, opts ...grpc.CallOption) (*TerminateRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateRunResponse)
	err := c.cc.Invoke(ctx, WorkflowService_TerminateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SignalRun(ctx context.Context, in *SignalRunRequest, opts ...grpc.CallOption) (*SignalRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalRunResponse)
	err := c.cc.Invoke(ctx, WorkflowService_SignalRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
//
// WorkflowService is the console's view of the services' Temporal
// workflows (§9): what they declare, starting one with a form, the runs
// through Temporal visibility and the actions on a run. backplane reaches
// Temporal through its own client (BACKPLANE_TEMPORAL_ADDR); without one
// the Temporal-backed calls fail with UNAVAILABLE. Runs the console starts
// carry memo source = console:<session> (§14).
//
// GetRun, CancelRun, TerminateRun and SignalRun address any workflow id of
// backplane's namespace, not only runs on a service's queue: binding and
// rule runs live on backplane's own queue, and the console session is an
// installation operator.
type WorkflowServiceServer interface {
	// Workflows the latest manifests declare: workflows[] and activities
	// of kind WORKFLOW, with the workers polling their task queue.
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	// Starts a declared workflow on the service's task queue. A workflow_id
	// that has a running run is ALREADY_EXISTS; a closed one starts a new run.
	StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error)
	// Runs on a service's task queue (or its hook calls), newest start first
	// where the visibility store sorts (Elasticsearch). SQL visibility (the
	// dev server, PostgreSQL, MySQL) refuses ORDER BY; there the order is
	// Temporal's own: running runs first, then by close time, newest first.
	// ListRunsResponse.query shows which query ran.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	// One run: status, input, result or failure, pending activities and
	// its history as a timeline.
	GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	// Requests cancellation: the workflow sees it and may clean up.
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	// Ends the run at once, without the workflow's code.
	TerminateRun(context.Context, *TerminateRunRequest) (*TerminateRunResponse, error)
	// Sends a signal with a JSON argument, or none.
	SignalRun(context.Context, *SignalRunRequest) (*SignalRunResponse, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedWorkflowServiceServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedWorkflowServiceServer) GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedWorkflowServiceServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedWorkflowServiceServer) TerminateRun(context.Context, *TerminateRunRequest) (*TerminateRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateRun not implemented")
}
func (UnimplementedWorkflowServiceServer) SignalRun(context.Context, *SignalRunRequest) (*SignalRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalRun not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_TerminateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).TerminateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_TerminateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).TerminateRun(ctx, req.(*TerminateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SignalRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SignalRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_SignalRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SignalRun(ctx, req.(*SignalRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorkflows",
			Handler:    _WorkflowService_ListWorkflows_Handler,
		},
		{
			MethodName: "StartWorkflow",
			Handler:    _WorkflowService_StartWorkflow_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _WorkflowService_ListRuns_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _WorkflowService_GetRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _WorkflowService_CancelRun_Handler,
		},
		{
			MethodName: "TerminateRun",
			Handler:    _WorkflowService_TerminateRun_Handler,
		},
		{
			MethodName: "SignalRun",
			Handler:    _WorkflowService_SignalRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backplanepb/console/v1/workflows.proto",
}

const (
	ScheduleService_ListSchedules_FullMethodName   = "/backplane.console.v1.ScheduleService/ListSchedules"
	ScheduleService_PauseSchedule_FullMethodName   = "/backplane.console.v1.ScheduleService/PauseSchedule"
	ScheduleService_UnpauseSchedule_FullMethodName = "/backplane.console.v1.ScheduleService/UnpauseSchedule"
	ScheduleService_TriggerSchedule_FullMethodName = "/backplane.console.v1.ScheduleService/TriggerSchedule"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScheduleService is the services' Temporal Schedules (§9): the
// declarations with what Temporal says about them, and the operator's
// actions. A pause or unpause lasts until the declaration changes (the
// SDK's reconciliation leaves a matching schedule alone).
type ScheduleServiceClient interface {
	// Schedules declared by the latest manifests, plus schedules in
	// Temporal under a service's prefix that no manifest declares.
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error)
	UnpauseSchedule(ctx context.Context, in *UnpauseScheduleRequest, opts ...grpc.CallOption) (*UnpauseScheduleResponse, error)
	// Starts the schedule's action now, whatever its overlap policy. The run
	// carries the schedule's action (memo included): Temporal takes no memo
	// on a trigger, so who triggered it is in the audit, not on the run.
	TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, ScheduleService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_PauseSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) UnpauseSchedule(ctx context.Context, in *UnpauseScheduleRequest, opts ...grpc.CallOption) (*UnpauseScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpauseScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_UnpauseSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) TriggerSchedule(ctx context.Context, in *TriggerScheduleRequest, opts ...grpc.CallOption) (*TriggerScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_TriggerSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility.
//
// ScheduleService is the services' Temporal Schedules (§9): the
// declarations with what Temporal says about them, and the operator's
// actions. A pause or unpause lasts until the declaration changes (the
// SDK's reconciliation leaves a matching schedule alone).
type ScheduleServiceServer interface {
	// Schedules declared by the latest manifests, plus schedules in
	// Temporal under a service's prefix that no manifest declares.
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error)
	UnpauseSchedule(context.Context, *UnpauseScheduleRequest) (*UnpauseScheduleResponse, error)
	// Starts the schedule's action now, whatever its overlap policy. The run
	// carries the schedule's action (memo included): Temporal takes no memo
	// on a trigger, so who triggered it is in the audit, not on the run.
	TriggerSchedule(context.Context, *TriggerScheduleRequest) (*TriggerScheduleResponse, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleServiceServer struct{}

func (UnimplementedScheduleServiceServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedScheduleServiceServer) PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) UnpauseSchedule(context.Context, *UnpauseScheduleRequest) (*UnpauseScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpauseSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) TriggerSchedule(context.Context, *TriggerScheduleRequest) (*TriggerScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}
func (UnimplementedScheduleServiceServer) testEmbeddedByValue()                         {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	// If the following call panics, it indicates UnimplementedScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_PauseSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).PauseSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_PauseSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).PauseSchedule(ctx, req.(*PauseScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_UnpauseSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpauseScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).UnpauseSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_UnpauseSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).UnpauseSchedule(ctx, req.(*UnpauseScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_TriggerSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).TriggerSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_TriggerSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).TriggerSchedule(ctx, req.(*TriggerScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backplane.console.v1.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSchedules",
			Handler:    _ScheduleService_ListSchedules_Handler,
		},
		{
			MethodName: "PauseSchedule",
			Handler:    _ScheduleService_PauseSchedule_Handler,
		},
		{
			MethodName: "UnpauseSchedule",
			Handler:    _ScheduleService_UnpauseSchedule_Handler,
		},
		{
			MethodName: "TriggerSchedule",
			Handler:    _ScheduleService_TriggerSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backplanepb/console/v1/workflows.proto",
}
