// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/hello/v1/hello.proto

package hellov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type CountdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint32                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownRequest) Reset() {
	*x = CountdownRequest{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownRequest) ProtoMessage() {}

func (x *CountdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownRequest.ProtoReflect.Descriptor instead.
func (*CountdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{2}
}

func (x *CountdownRequest) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

type CountdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          uint32                 `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownResponse) Reset() {
	*x = CountdownResponse{}
	mi := &file_proto_hello_v1_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownResponse) ProtoMessage() {}

func (x *CountdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_v1_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownResponse.ProtoReflect.Descriptor instead.
func (*CountdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_v1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *CountdownResponse) GetLeft() uint32 {
	if x != nil {
		return x.Left
	}
	return 0
}

var File_proto_hello_v1_hello_proto protoreflect.FileDescriptor

const file_proto_hello_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/hello/v1/hello.proto\x12\bhello.v1\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\rGreetResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"&\n" +
	"\x10CountdownRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\rR\x04from\"'\n" +
	"\x11CountdownResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\rR\x04left2\x90\x01\n" +
	"\fHelloService\x128\n" +
	"\x05Greet\x12\x16.hello.v1.GreetRequest\x1a\x17.hello.v1.GreetResponse\x12F\n" +
	"\tCountdown\x12\x1a.hello.v1.CountdownRequest\x1a\x1b.hello.v1.CountdownResponse0\x01BEZCgithub.com/gopherex/backplane/examples/hello/proto/hello/v1;hellov1b\x06proto3"

var (
	file_proto_hello_v1_hello_proto_rawDescOnce sync.Once
	file_proto_hello_v1_hello_proto_rawDescData []byte
)

func file_proto_hello_v1_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_v1_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_v1_hello_proto_rawDesc), len(file_proto_hello_v1_hello_proto_rawDesc)))
	})
	return file_proto_hello_v1_hello_proto_rawDescData
}

var file_proto_hello_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_hello_v1_hello_proto_goTypes = []any{
	(*GreetRequest)(nil),      // 0: hello.v1.GreetRequest
	(*GreetResponse)(nil),     // 1: hello.v1.GreetResponse
	(*CountdownRequest)(nil),  // 2: hello.v1.CountdownRequest
	(*CountdownResponse)(nil), // 3: hello.v1.CountdownResponse
}
var file_proto_hello_v1_hello_proto_depIdxs = []int32{
	0, // 0: hello.v1.HelloService.Greet:input_type -> hello.v1.GreetRequest
	2, // 1: hello.v1.HelloService.Countdown:input_type -> hello.v1.CountdownRequest
	1, // 2: hello.v1.HelloService.Greet:output_type -> hello.v1.GreetResponse
	3, // 3: hello.v1.HelloService.Countdown:output_type -> hello.v1.CountdownResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_v1_hello_proto_init() }
func file_proto_hello_v1_hello_proto_init() {
	if File_proto_hello_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_v1_hello_proto_rawDesc), len(file_proto_hello_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_v1_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_v1_hello_proto_depIdxs,
		MessageInfos:      file_proto_hello_v1_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_v1_hello_proto = out.File
	file_proto_hello_v1_hello_proto_goTypes = nil
	file_proto_hello_v1_hello_proto_depIdxs = nil
}
