// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/hello/console/v1/admin.proto

package helloconsolev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_hello_console_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_console_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_console_v1_admin_proto_rawDescGZIP(), []int{0}
}

type GetStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Greetings       uint64                 `protobuf:"varint,1,opt,name=greetings,proto3" json:"greetings,omitempty"`
	CurrentGreeting string                 `protobuf:"bytes,2,opt,name=current_greeting,json=currentGreeting,proto3" json:"current_greeting,omitempty"`
	// Greetings the audit reactor saw come off the event stream.
	Audited uint64 `protobuf:"varint,3,opt,name=audited,proto3" json:"audited,omitempty"`
	// Whether the optional cache is there right now.
	CachePresent  bool `protobuf:"varint,4,opt,name=cache_present,json=cachePresent,proto3" json:"cache_present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_hello_console_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_console_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_console_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetGreetings() uint64 {
	if x != nil {
		return x.Greetings
	}
	return 0
}

func (x *GetStatsResponse) GetCurrentGreeting() string {
	if x != nil {
		return x.CurrentGreeting
	}
	return ""
}

func (x *GetStatsResponse) GetAudited() uint64 {
	if x != nil {
		return x.Audited
	}
	return 0
}

func (x *GetStatsResponse) GetCachePresent() bool {
	if x != nil {
		return x.CachePresent
	}
	return false
}

var File_proto_hello_console_v1_admin_proto protoreflect.FileDescriptor

const file_proto_hello_console_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\"proto/hello/console/v1/admin.proto\x12\x10hello.console.v1\"\x11\n" +
	"\x0fGetStatsRequest\"\x9a\x01\n" +
	"\x10GetStatsResponse\x12\x1c\n" +
	"\tgreetings\x18\x01 \x01(\x04R\tgreetings\x12)\n" +
	"\x10current_greeting\x18\x02 \x01(\tR\x0fcurrentGreeting\x12\x18\n" +
	"\aaudited\x18\x03 \x01(\x04R\aaudited\x12#\n" +
	"\rcache_present\x18\x04 \x01(\bR\fcachePresent2a\n" +
	"\fAdminService\x12Q\n" +
	"\bGetStats\x12!.hello.console.v1.GetStatsRequest\x1a\".hello.console.v1.GetStatsResponseBTZRgithub.com/gopherex/backplane/examples/hello/proto/hello/console/v1;helloconsolev1b\x06proto3"

var (
	file_proto_hello_console_v1_admin_proto_rawDescOnce sync.Once
	file_proto_hello_console_v1_admin_proto_rawDescData []byte
)

func file_proto_hello_console_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_hello_console_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_hello_console_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_console_v1_admin_proto_rawDesc), len(file_proto_hello_console_v1_admin_proto_rawDesc)))
	})
	return file_proto_hello_console_v1_admin_proto_rawDescData
}

var file_proto_hello_console_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hello_console_v1_admin_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: hello.console.v1.GetStatsRequest
	(*GetStatsResponse)(nil), // 1: hello.console.v1.GetStatsResponse
}
var file_proto_hello_console_v1_admin_proto_depIdxs = []int32{
	0, // 0: hello.console.v1.AdminService.GetStats:input_type -> hello.console.v1.GetStatsRequest
	1, // 1: hello.console.v1.AdminService.GetStats:output_type -> hello.console.v1.GetStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_console_v1_admin_proto_init() }
func file_proto_hello_console_v1_admin_proto_init() {
	if File_proto_hello_console_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_console_v1_admin_proto_rawDesc), len(file_proto_hello_console_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_console_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_hello_console_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_hello_console_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_hello_console_v1_admin_proto = out.File
	file_proto_hello_console_v1_admin_proto_goTypes = nil
	file_proto_hello_console_v1_admin_proto_depIdxs = nil
}
