import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const base = `${process.env.BACKPLANE_DEV_URL ?? 'http://127.0.0.1:10000'}/backplane`;
const browser = await chromium.launch();
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 950 } });
  const page = await context.newPage(), failures = [];
  page.on('pageerror', (error) => failures.push(error.message));
  await page.goto(`${base}/s/hello/settings`);
  const token = page.getByLabel('Operator token', { exact: true });
  await expect(token).toBeFocused();
  const bounds = await page.locator('.login-main').boundingBox();
  assert.ok(Math.abs(bounds.x + bounds.width / 2 - 720) < 2);
  assert.ok(Math.abs(bounds.y + bounds.height / 2 - 475) < 2);
  await expect(page.getByRole('button', { name: 'Log in', exact: true })).toBeDisabled();
  await page.screenshot({ path: '/tmp/backplane-login-dark.png', animations: 'disabled' });
  assert.deepEqual((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations, []);
  await page.getByRole('button', { name: 'Light theme' }).click();
  await page.screenshot({ path: '/tmp/backplane-login-light.png', animations: 'disabled' });
  assert.deepEqual((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations, []);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/backplane-login-mobile.png', animations: 'disabled' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await token.fill('invalid-operator-token');
  await page.getByRole('button', { name: 'Show token' }).click();
  await expect(token).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Hide token' }).click();
  await expect(token).toHaveAttribute('type', 'password');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('This token was not accepted. Check it and try again.');
  await expect(token).toHaveAttribute('aria-invalid', 'true');
  await expect(token).toBeFocused();
  assert.deepEqual((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations, []);
  // A delayed failure shows pending state and cannot submit twice.
  let release, requests = 0;
  const gate = new Promise((resolve) => { release = resolve; });
  await page.route('**/auth/login', async (route) => { requests++; await gate; await route.fulfill({ status: 503, body: 'Unavailable' }); });
  await token.fill('another-token');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Logging in…' })).toBeDisabled();
  await token.press('Enter');
  release();
  await expect(page.getByRole('alert')).toHaveText('Cannot reach Backplane right now. Please try again.');
  assert.equal(requests, 1);
  await page.unroute('**/auth/login');
  await token.fill(process.env.DEV_ADMIN_TOKEN ?? 'dev-admin-token-change-me');
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page.getByLabel('Display name')).toBeVisible();
  await expect(page).toHaveURL(`${base}/s/hello/settings`);
  await page.getByRole('button', { name: 'Session', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Log out', exact: true }).click();
  await expect(token).toHaveValue('');
  await expect(token).toHaveAttribute('type', 'password');
  // Session-check outages keep the same composed screen and recover explicitly.
  await page.route('**/auth/session', (route) => route.fulfill({ status: 503, body: 'Unavailable' }));
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Backplane is unavailable' })).toBeVisible();
  await page.unroute('**/auth/session');
  await page.getByRole('button', { name: 'Try again' }).click();
  await expect(token).toBeVisible();
  assert.deepEqual(failures, []);
  console.log('Login acceptance passed: centered layout, themes, mobile, accessibility, rejection, pending/duplicate prevention, deep-link login, logout and outage recovery');
} finally { await browser.close(); }
