// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/v1/instance.proto

package backplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigSource int32

const (
	ConfigSource_CONFIG_SOURCE_UNSPECIFIED ConfigSource = 0
	ConfigSource_CONFIG_SOURCE_DEFAULT     ConfigSource = 1
	ConfigSource_CONFIG_SOURCE_FILE        ConfigSource = 2
	ConfigSource_CONFIG_SOURCE_ENV         ConfigSource = 3
	ConfigSource_CONFIG_SOURCE_KV          ConfigSource = 4
)

// Enum value maps for ConfigSource.
var (
	ConfigSource_name = map[int32]string{
		0: "CONFIG_SOURCE_UNSPECIFIED",
		1: "CONFIG_SOURCE_DEFAULT",
		2: "CONFIG_SOURCE_FILE",
		3: "CONFIG_SOURCE_ENV",
		4: "CONFIG_SOURCE_KV",
	}
	ConfigSource_value = map[string]int32{
		"CONFIG_SOURCE_UNSPECIFIED": 0,
		"CONFIG_SOURCE_DEFAULT":     1,
		"CONFIG_SOURCE_FILE":        2,
		"CONFIG_SOURCE_ENV":         3,
		"CONFIG_SOURCE_KV":          4,
	}
)

func (x ConfigSource) Enum() *ConfigSource {
	p := new(ConfigSource)
	*p = x
	return p
}

func (x ConfigSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigSource) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_instance_proto_enumTypes[0].Descriptor()
}

func (ConfigSource) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_instance_proto_enumTypes[0]
}

func (x ConfigSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigSource.Descriptor instead.
func (ConfigSource) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_instance_proto_rawDescGZIP(), []int{0}
}

// InstanceState is written by the SDK to Consul KV
// `backplane/services/<service>/instances/<id>` under a session with TTL, so
// it dies with the instance. The console shows what is really applied; the
// console relay takes address and port from here.
type InstanceState struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service      string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version      string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Address      string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PlatformPort uint32                 `protobuf:"varint,5,opt,name=platform_port,json=platformPort,proto3" json:"platform_port,omitempty"`
	StartedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Effective configuration as JSON, secrets masked.
	Config []byte `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	// Source of every configuration path.
	Sources map[string]ConfigSource `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=backplane.v1.ConfigSource"`
	// Revision from Consul KV `config/<service>/_revision` that is applied.
	ConfigRevision uint64 `protobuf:"varint,9,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	// Why the last KV update was not applied; empty when applied.
	ConfigError   string `protobuf:"bytes,10,opt,name=config_error,json=configError,proto3" json:"config_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceState) Reset() {
	*x = InstanceState{}
	mi := &file_backplanepb_v1_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceState) ProtoMessage() {}

func (x *InstanceState) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceState.ProtoReflect.Descriptor instead.
func (*InstanceState) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_instance_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceState) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InstanceState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstanceState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *InstanceState) GetPlatformPort() uint32 {
	if x != nil {
		return x.PlatformPort
	}
	return 0
}

func (x *InstanceState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *InstanceState) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InstanceState) GetSources() map[string]ConfigSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *InstanceState) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *InstanceState) GetConfigError() string {
	if x != nil {
		return x.ConfigError
	}
	return ""
}

var File_backplanepb_v1_instance_proto protoreflect.FileDescriptor

const file_backplanepb_v1_instance_proto_rawDesc = "" +
	"\n" +
	"\x1dbackplanepb/v1/instance.proto\x12\fbackplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x03\n" +
	"\rInstanceState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12#\n" +
	"\rplatform_port\x18\x05 \x01(\rR\fplatformPort\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x16\n" +
	"\x06config\x18\a \x01(\fR\x06config\x12B\n" +
	"\asources\x18\b \x03(\v2(.backplane.v1.InstanceState.SourcesEntryR\asources\x12'\n" +
	"\x0fconfig_revision\x18\t \x01(\x04R\x0econfigRevision\x12!\n" +
	"\fconfig_error\x18\n" +
	" \x01(\tR\vconfigError\x1aV\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1a.backplane.v1.ConfigSourceR\x05value:\x028\x01*\x8d\x01\n" +
	"\fConfigSource\x12\x1d\n" +
	"\x19CONFIG_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONFIG_SOURCE_DEFAULT\x10\x01\x12\x16\n" +
	"\x12CONFIG_SOURCE_FILE\x10\x02\x12\x15\n" +
	"\x11CONFIG_SOURCE_ENV\x10\x03\x12\x14\n" +
	"\x10CONFIG_SOURCE_KV\x10\x04B:Z8github.com/gopherex/backplane/backplanepb/v1;backplanev1b\x06proto3"

var (
	file_backplanepb_v1_instance_proto_rawDescOnce sync.Once
	file_backplanepb_v1_instance_proto_rawDescData []byte
)

func file_backplanepb_v1_instance_proto_rawDescGZIP() []byte {
	file_backplanepb_v1_instance_proto_rawDescOnce.Do(func() {
		file_backplanepb_v1_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backplanepb_v1_instance_proto_rawDesc), len(file_backplanepb_v1_instance_proto_rawDesc)))
	})
	return file_backplanepb_v1_instance_proto_rawDescData
}

var file_backplanepb_v1_instance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backplanepb_v1_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backplanepb_v1_instance_proto_goTypes = []any{
	(ConfigSource)(0),             // 0: backplane.v1.ConfigSource
	(*InstanceState)(nil),         // 1: backplane.v1.InstanceState
	nil,                           // 2: backplane.v1.InstanceState.SourcesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_backplanepb_v1_instance_proto_depIdxs = []int32{
	3, // 0: backplane.v1.InstanceState.started_at:type_name -> google.protobuf.Timestamp
	2, // 1: backplane.v1.InstanceState.sources:type_name -> backplane.v1.InstanceState.SourcesEntry
	0, // 2: backplane.v1.InstanceState.SourcesEntry.value:type_name -> backplane.v1.ConfigSource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_backplanepb_v1_instance_proto_init() }
func file_backplanepb_v1_instance_proto_init() {
	if File_backplanepb_v1_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backplanepb_v1_instance_proto_rawDesc), len(file_backplanepb_v1_instance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backplanepb_v1_instance_proto_goTypes,
		DependencyIndexes: file_backplanepb_v1_instance_proto_depIdxs,
		EnumInfos:         file_backplanepb_v1_instance_proto_enumTypes,
		MessageInfos:      file_backplanepb_v1_instance_proto_msgTypes,
	}.Build()
	File_backplanepb_v1_instance_proto = out.File
	file_backplanepb_v1_instance_proto_goTypes = nil
	file_backplanepb_v1_instance_proto_depIdxs = nil
}
