// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: backplanepb/v1/manifest.proto

package backplanev1

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeKind int32

const (
	NodeKind_NODE_KIND_UNSPECIFIED NodeKind = 0
	NodeKind_NODE_KIND_COMPONENT   NodeKind = 1
	NodeKind_NODE_KIND_DEPENDENCY  NodeKind = 2
	NodeKind_NODE_KIND_SINGLETON   NodeKind = 3
)

// Enum value maps for NodeKind.
var (
	NodeKind_name = map[int32]string{
		0: "NODE_KIND_UNSPECIFIED",
		1: "NODE_KIND_COMPONENT",
		2: "NODE_KIND_DEPENDENCY",
		3: "NODE_KIND_SINGLETON",
	}
	NodeKind_value = map[string]int32{
		"NODE_KIND_UNSPECIFIED": 0,
		"NODE_KIND_COMPONENT":   1,
		"NODE_KIND_DEPENDENCY":  2,
		"NODE_KIND_SINGLETON":   3,
	}
)

func (x NodeKind) Enum() *NodeKind {
	p := new(NodeKind)
	*p = x
	return p
}

func (x NodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_manifest_proto_enumTypes[0].Descriptor()
}

func (NodeKind) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_manifest_proto_enumTypes[0]
}

func (x NodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeKind.Descriptor instead.
func (NodeKind) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{0}
}

type SchemaFormat int32

const (
	SchemaFormat_SCHEMA_FORMAT_UNSPECIFIED SchemaFormat = 0
	SchemaFormat_SCHEMA_FORMAT_OPENAPI     SchemaFormat = 1
	SchemaFormat_SCHEMA_FORMAT_GRAPHQL     SchemaFormat = 2
)

// Enum value maps for SchemaFormat.
var (
	SchemaFormat_name = map[int32]string{
		0: "SCHEMA_FORMAT_UNSPECIFIED",
		1: "SCHEMA_FORMAT_OPENAPI",
		2: "SCHEMA_FORMAT_GRAPHQL",
	}
	SchemaFormat_value = map[string]int32{
		"SCHEMA_FORMAT_UNSPECIFIED": 0,
		"SCHEMA_FORMAT_OPENAPI":     1,
		"SCHEMA_FORMAT_GRAPHQL":     2,
	}
)

func (x SchemaFormat) Enum() *SchemaFormat {
	p := new(SchemaFormat)
	*p = x
	return p
}

func (x SchemaFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_manifest_proto_enumTypes[1].Descriptor()
}

func (SchemaFormat) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_manifest_proto_enumTypes[1]
}

func (x SchemaFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaFormat.Descriptor instead.
func (SchemaFormat) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{1}
}

type RouteKind int32

const (
	RouteKind_ROUTE_KIND_UNSPECIFIED RouteKind = 0
	RouteKind_ROUTE_KIND_HTTP        RouteKind = 1
	RouteKind_ROUTE_KIND_GRPC        RouteKind = 2
	RouteKind_ROUTE_KIND_CONNECT     RouteKind = 3
	RouteKind_ROUTE_KIND_WS_PROTO    RouteKind = 4
	RouteKind_ROUTE_KIND_GRAPHQL     RouteKind = 5
)

// Enum value maps for RouteKind.
var (
	RouteKind_name = map[int32]string{
		0: "ROUTE_KIND_UNSPECIFIED",
		1: "ROUTE_KIND_HTTP",
		2: "ROUTE_KIND_GRPC",
		3: "ROUTE_KIND_CONNECT",
		4: "ROUTE_KIND_WS_PROTO",
		5: "ROUTE_KIND_GRAPHQL",
	}
	RouteKind_value = map[string]int32{
		"ROUTE_KIND_UNSPECIFIED": 0,
		"ROUTE_KIND_HTTP":        1,
		"ROUTE_KIND_GRPC":        2,
		"ROUTE_KIND_CONNECT":     3,
		"ROUTE_KIND_WS_PROTO":    4,
		"ROUTE_KIND_GRAPHQL":     5,
	}
)

func (x RouteKind) Enum() *RouteKind {
	p := new(RouteKind)
	*p = x
	return p
}

func (x RouteKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteKind) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_manifest_proto_enumTypes[2].Descriptor()
}

func (RouteKind) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_manifest_proto_enumTypes[2]
}

func (x RouteKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteKind.Descriptor instead.
func (RouteKind) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{2}
}

type ActivityKind int32

const (
	ActivityKind_ACTIVITY_KIND_UNSPECIFIED ActivityKind = 0
	// A Temporal activity on the service's queue.
	ActivityKind_ACTIVITY_KIND_ACTIVITY ActivityKind = 1
	// A Temporal workflow on the service's queue, run as a child workflow.
	ActivityKind_ACTIVITY_KIND_WORKFLOW ActivityKind = 2
)

// Enum value maps for ActivityKind.
var (
	ActivityKind_name = map[int32]string{
		0: "ACTIVITY_KIND_UNSPECIFIED",
		1: "ACTIVITY_KIND_ACTIVITY",
		2: "ACTIVITY_KIND_WORKFLOW",
	}
	ActivityKind_value = map[string]int32{
		"ACTIVITY_KIND_UNSPECIFIED": 0,
		"ACTIVITY_KIND_ACTIVITY":    1,
		"ACTIVITY_KIND_WORKFLOW":    2,
	}
)

func (x ActivityKind) Enum() *ActivityKind {
	p := new(ActivityKind)
	*p = x
	return p
}

func (x ActivityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_manifest_proto_enumTypes[3].Descriptor()
}

func (ActivityKind) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_manifest_proto_enumTypes[3]
}

func (x ActivityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityKind.Descriptor instead.
func (ActivityKind) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{3}
}

// What a start does while the previous run is still going.
type ScheduleOverlap int32

const (
	ScheduleOverlap_SCHEDULE_OVERLAP_UNSPECIFIED ScheduleOverlap = 0
	// Do not start (the default).
	ScheduleOverlap_SCHEDULE_OVERLAP_SKIP ScheduleOverlap = 1
	// Start once the running one ends; at most one waits.
	ScheduleOverlap_SCHEDULE_OVERLAP_BUFFER_ONE ScheduleOverlap = 2
	// Start every missed one after the running one ends.
	ScheduleOverlap_SCHEDULE_OVERLAP_BUFFER_ALL ScheduleOverlap = 3
	// Cancel the running one, then start.
	ScheduleOverlap_SCHEDULE_OVERLAP_CANCEL_OTHER ScheduleOverlap = 4
	// Terminate the running one, then start.
	ScheduleOverlap_SCHEDULE_OVERLAP_TERMINATE_OTHER ScheduleOverlap = 5
	// Start regardless.
	ScheduleOverlap_SCHEDULE_OVERLAP_ALLOW_ALL ScheduleOverlap = 6
)

// Enum value maps for ScheduleOverlap.
var (
	ScheduleOverlap_name = map[int32]string{
		0: "SCHEDULE_OVERLAP_UNSPECIFIED",
		1: "SCHEDULE_OVERLAP_SKIP",
		2: "SCHEDULE_OVERLAP_BUFFER_ONE",
		3: "SCHEDULE_OVERLAP_BUFFER_ALL",
		4: "SCHEDULE_OVERLAP_CANCEL_OTHER",
		5: "SCHEDULE_OVERLAP_TERMINATE_OTHER",
		6: "SCHEDULE_OVERLAP_ALLOW_ALL",
	}
	ScheduleOverlap_value = map[string]int32{
		"SCHEDULE_OVERLAP_UNSPECIFIED":     0,
		"SCHEDULE_OVERLAP_SKIP":            1,
		"SCHEDULE_OVERLAP_BUFFER_ONE":      2,
		"SCHEDULE_OVERLAP_BUFFER_ALL":      3,
		"SCHEDULE_OVERLAP_CANCEL_OTHER":    4,
		"SCHEDULE_OVERLAP_TERMINATE_OTHER": 5,
		"SCHEDULE_OVERLAP_ALLOW_ALL":       6,
	}
)

func (x ScheduleOverlap) Enum() *ScheduleOverlap {
	p := new(ScheduleOverlap)
	*p = x
	return p
}

func (x ScheduleOverlap) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleOverlap) Descriptor() protoreflect.EnumDescriptor {
	return file_backplanepb_v1_manifest_proto_enumTypes[4].Descriptor()
}

func (ScheduleOverlap) Type() protoreflect.EnumType {
	return &file_backplanepb_v1_manifest_proto_enumTypes[4]
}

func (x ScheduleOverlap) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleOverlap.Descriptor instead.
func (ScheduleOverlap) EnumDescriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{4}
}

// Manifest is everything a service declares. The SDK assembles it at start
// and writes it to Consul KV `backplane/services/<service>/manifests/<version>`
// as protobuf binary. Names are mandatory; schemas are optional.
type Manifest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Service    string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version    string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SdkVersion string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// The service configuration: one struct; Live fields are listed in
	// config.live and are the only ones Consul KV overrides.
	Config *ConfigSection `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// External API: proxied by Envoy, informational for the console.
	Routes []*Route `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	// Internal API: full gRPC service names on the platform port; the only
	// methods the console relay forwards.
	InternalServices []string    `protobuf:"bytes,7,rep,name=internal_services,json=internalServices,proto3" json:"internal_services,omitempty"`
	Events           []*Event    `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	Hooks            []*Hook     `protobuf:"bytes,9,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Activities       []*Activity `protobuf:"bytes,10,rep,name=activities,proto3" json:"activities,omitempty"`
	Ui               *UI         `protobuf:"bytes,11,opt,name=ui,proto3" json:"ui,omitempty"`
	// The node tree the author composed, depth-first in creation (= start)
	// order.
	Nodes []*Node `protobuf:"bytes,12,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Serialized FileDescriptorSet covering every service named by a managed
	// route (Route.services) and by internal_services, with transitive
	// imports: stored once instead of per route.
	Descriptors []byte `protobuf:"bytes,13,opt,name=descriptors,proto3" json:"descriptors,omitempty"`
	// Events the service reacts to.
	Subscriptions []*Subscription `protobuf:"bytes,14,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// Temporal Schedules of the service's own workflows.
	Schedules []*Schedule `protobuf:"bytes,15,rep,name=schedules,proto3" json:"schedules,omitempty"`
	// The service's own workflows the console may start (§9).
	Workflows []*Workflow `protobuf:"bytes,16,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// Optional telemetry view presets. Absence uses service.name convention;
	// an explicitly empty declaration disables presets, never signal ingestion.
	Telemetry     *TelemetrySources `protobuf:"bytes,17,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Manifest) GetConfig() *ConfigSection {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Manifest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Manifest) GetInternalServices() []string {
	if x != nil {
		return x.InternalServices
	}
	return nil
}

func (x *Manifest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Manifest) GetHooks() []*Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *Manifest) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *Manifest) GetUi() *UI {
	if x != nil {
		return x.Ui
	}
	return nil
}

func (x *Manifest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Manifest) GetDescriptors() []byte {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *Manifest) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Manifest) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *Manifest) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *Manifest) GetTelemetry() *TelemetrySources {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

// Selectors are OR alternatives; attributes within one selector are AND exact
// matches against OTel resource attributes. They never grant access or identify
// trusted senders. The query driver maps resource names to storage fields.
type TelemetrySourceSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      map[string]string      `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySourceSelector) Reset() {
	*x = TelemetrySourceSelector{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySourceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySourceSelector) ProtoMessage() {}

func (x *TelemetrySourceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySourceSelector.ProtoReflect.Descriptor instead.
func (*TelemetrySourceSelector) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetrySourceSelector) GetResource() map[string]string {
	if x != nil {
		return x.Resource
	}
	return nil
}

type TelemetrySources struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Selectors     []*TelemetrySourceSelector `protobuf:"bytes,1,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySources) Reset() {
	*x = TelemetrySources{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySources) ProtoMessage() {}

func (x *TelemetrySources) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySources.ProtoReflect.Descriptor instead.
func (*TelemetrySources) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetrySources) GetSelectors() []*TelemetrySourceSelector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

// The configuration. `keys` is the declaration; `schema` is optional and,
// when present, drives forms, validation and secret masking.
type ConfigSection struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Keys   []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Schema *schemapb.Schema       `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// Paths of Live fields, dot-separated ("postgres.log_level").
	Live          []string `protobuf:"bytes,3,rep,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSection) Reset() {
	*x = ConfigSection{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSection) ProtoMessage() {}

func (x *ConfigSection) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSection.ProtoReflect.Descriptor instead.
func (*ConfigSection) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSection) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ConfigSection) GetSchema() *schemapb.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ConfigSection) GetLive() []string {
	if x != nil {
		return x.Live
	}
	return nil
}

// A node of the service tree: component, dependency or singleton.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Place in the tree: "users", "users/templates".
	Path string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind NodeKind `protobuf:"varint,2,opt,name=kind,proto3,enum=backplane.v1.NodeKind" json:"kind,omitempty"`
	// Optional dependencies do not hold readiness.
	Optional      bool `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Node) GetKind() NodeKind {
	if x != nil {
		return x.Kind
	}
	return NodeKind_NODE_KIND_UNSPECIFIED
}

func (x *Node) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// A public route for Envoy.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path prefix ("/api/"); gRPC routes use "/<full service name>/".
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Host header to match in addition to the prefix; empty matches any host.
	Host string    `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Kind RouteKind `protobuf:"varint,3,opt,name=kind,proto3,enum=backplane.v1.RouteKind" json:"kind,omitempty"`
	// Port of the external API this route leads to; 0 = the port registered
	// in Consul.
	Port uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// gRPC, Connect and ws-proto: full names of the services behind the
	// route; their descriptors are in Manifest.descriptors unless the route
	// carries its own.
	Services []string `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	// Schema for transcoding and the console's API tab; optional.
	//
	// Types that are valid to be assigned to Schema:
	//
	//	*Route_Openapi
	//	*Route_Descriptors
	//	*Route_Graphql
	//	*Route_Bundle
	Schema isRoute_Schema `protobuf_oneof:"schema"`
	// Envoy policy; unset fields take the platform defaults.
	Policy        *RoutePolicy `protobuf:"bytes,9,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *Route) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Route) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Route) GetKind() RouteKind {
	if x != nil {
		return x.Kind
	}
	return RouteKind_ROUTE_KIND_UNSPECIFIED
}

func (x *Route) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Route) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Route) GetSchema() isRoute_Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Route) GetOpenapi() []byte {
	if x != nil {
		if x, ok := x.Schema.(*Route_Openapi); ok {
			return x.Openapi
		}
	}
	return nil
}

func (x *Route) GetDescriptors() []byte {
	if x != nil {
		if x, ok := x.Schema.(*Route_Descriptors); ok {
			return x.Descriptors
		}
	}
	return nil
}

func (x *Route) GetGraphql() []byte {
	if x != nil {
		if x, ok := x.Schema.(*Route_Graphql); ok {
			return x.Graphql
		}
	}
	return nil
}

func (x *Route) GetBundle() *APISchemaBundle {
	if x != nil {
		if x, ok := x.Schema.(*Route_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

func (x *Route) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type isRoute_Schema interface {
	isRoute_Schema()
}

type Route_Openapi struct {
	// OpenAPI document (HTTP).
	Openapi []byte `protobuf:"bytes,5,opt,name=openapi,proto3,oneof"`
}

type Route_Descriptors struct {
	// Serialized FileDescriptorSet (gRPC, Connect, ws-proto).
	Descriptors []byte `protobuf:"bytes,6,opt,name=descriptors,proto3,oneof"`
}

type Route_Graphql struct {
	// Introspection result as JSON (GraphQL).
	Graphql []byte `protobuf:"bytes,7,opt,name=graphql,proto3,oneof"`
}

type Route_Bundle struct {
	// Files served by the SDK on the platform port, outside Consul KV.
	Bundle *APISchemaBundle `protobuf:"bytes,10,opt,name=bundle,proto3,oneof"`
}

func (*Route_Openapi) isRoute_Schema() {}

func (*Route_Descriptors) isRoute_Schema() {}

func (*Route_Graphql) isRoute_Schema() {}

func (*Route_Bundle) isRoute_Schema() {}

// An immutable API file snapshot, delivered separately from the manifest.
type APISchemaBundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Entry file relative to the bundle root; may reference other bundle files.
	Entry         string       `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	Format        SchemaFormat `protobuf:"varint,3,opt,name=format,proto3,enum=backplane.v1.SchemaFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISchemaBundle) Reset() {
	*x = APISchemaBundle{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISchemaBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISchemaBundle) ProtoMessage() {}

func (x *APISchemaBundle) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISchemaBundle.ProtoReflect.Descriptor instead.
func (*APISchemaBundle) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *APISchemaBundle) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *APISchemaBundle) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *APISchemaBundle) GetFormat() SchemaFormat {
	if x != nil {
		return x.Format
	}
	return SchemaFormat_SCHEMA_FORMAT_UNSPECIFIED
}

// What Envoy enforces on a route. Durations of zero mean "platform default";
// a stream route should set timeout explicitly (Envoy's default is 15s).
type RoutePolicy struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timeout     *durationpb.Duration   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IdleTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	Retry       *RetryPolicy           `protobuf:"bytes,3,opt,name=retry,proto3" json:"retry,omitempty"`
	Cors        *Cors                  `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	// 0 = platform default.
	MaxRequestBytes uint64 `protobuf:"varint,5,opt,name=max_request_bytes,json=maxRequestBytes,proto3" json:"max_request_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{7}
}

func (x *RoutePolicy) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RoutePolicy) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

func (x *RoutePolicy) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *RoutePolicy) GetCors() *Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *RoutePolicy) GetMaxRequestBytes() uint64 {
	if x != nil {
		return x.MaxRequestBytes
	}
	return 0
}

type RetryPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      uint32                 `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	PerTryTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=per_try_timeout,json=perTryTimeout,proto3" json:"per_try_timeout,omitempty"`
	// Envoy retry_on conditions ("5xx", "reset", "unavailable", ...).
	RetryOn       []string `protobuf:"bytes,3,rep,name=retry_on,json=retryOn,proto3" json:"retry_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{8}
}

func (x *RetryPolicy) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *RetryPolicy) GetPerTryTimeout() *durationpb.Duration {
	if x != nil {
		return x.PerTryTimeout
	}
	return nil
}

func (x *RetryPolicy) GetRetryOn() []string {
	if x != nil {
		return x.RetryOn
	}
	return nil
}

type Cors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origins       []string               `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	Headers       []string               `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	ExposeHeaders []string               `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	Credentials   bool                   `protobuf:"varint,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	MaxAge        *durationpb.Duration   `protobuf:"bytes,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cors) Reset() {
	*x = Cors{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cors) ProtoMessage() {}

func (x *Cors) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cors.ProtoReflect.Descriptor instead.
func (*Cors) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{9}
}

func (x *Cors) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *Cors) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Cors) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Cors) GetCredentials() bool {
	if x != nil {
		return x.Credentials
	}
	return false
}

func (x *Cors) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema        *schemapb.Schema       `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetSchema() *schemapb.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// A reactor: a durable consumer of another service's event.
type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full event name "<service>.<Event>".
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Durable consumer name, unique within the service: the node path of the
	// reactor plus the event name.
	Consumer      string `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{11}
}

func (x *Subscription) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Subscription) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

// An operation the service calls without implementing it.
type Hook struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input  *schemapb.Schema       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output *schemapb.Schema       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// The service cannot work without a binding.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Default deadline of a call; 0 = platform default.
	Timeout       *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Description   string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{12}
}

func (x *Hook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hook) GetInput() *schemapb.Schema {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Hook) GetOutput() *schemapb.Schema {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Hook) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Hook) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Hook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// An operation the service implements; a binding step target.
type Activity struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input  *schemapb.Schema       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output *schemapb.Schema       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Kind   ActivityKind           `protobuf:"varint,4,opt,name=kind,proto3,enum=backplane.v1.ActivityKind" json:"kind,omitempty"`
	// Defaults for a binding step calling it; the binding may override.
	StartToClose  *durationpb.Duration `protobuf:"bytes,5,opt,name=start_to_close,json=startToClose,proto3" json:"start_to_close,omitempty"`
	Heartbeat     *durationpb.Duration `protobuf:"bytes,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Retry         *RetryPolicy         `protobuf:"bytes,7,opt,name=retry,proto3" json:"retry,omitempty"`
	Description   string               `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{13}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetInput() *schemapb.Schema {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Activity) GetOutput() *schemapb.Schema {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Activity) GetKind() ActivityKind {
	if x != nil {
		return x.Kind
	}
	return ActivityKind_ACTIVITY_KIND_UNSPECIFIED
}

func (x *Activity) GetStartToClose() *durationpb.Duration {
	if x != nil {
		return x.StartToClose
	}
	return nil
}

func (x *Activity) GetHeartbeat() *durationpb.Duration {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *Activity) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// A workflow of the service the console may start with a form.
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temporal workflow type name.
	Name          string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         *schemapb.Schema `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *schemapb.Schema `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Description   string           `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{14}
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetInput() *schemapb.Schema {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Workflow) GetOutput() *schemapb.Schema {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UI struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content hash of the bundle served at GET /_backplane/ui/.
	Hash          string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SdkMajor      uint32 `protobuf:"varint,2,opt,name=sdk_major,json=sdkMajor,proto3" json:"sdk_major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UI) Reset() {
	*x = UI{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UI) ProtoMessage() {}

func (x *UI) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UI.ProtoReflect.Descriptor instead.
func (*UI) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{15}
}

func (x *UI) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UI) GetSdkMajor() uint32 {
	if x != nil {
		return x.SdkMajor
	}
	return 0
}

// A Temporal Schedule the service declares; the SDK reconciles it at start.
// Schedule id "<service>/<name>"; it starts the workflow on the service's
// task queue with workflow id "<service>/<name>-<time>".
type Schedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within the service: [A-Za-z][A-Za-z0-9_]*.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When the workflow starts.
	//
	// Types that are valid to be assigned to Spec:
	//
	//	*Schedule_Cron
	//	*Schedule_Every
	Spec isSchedule_Spec `protobuf_oneof:"spec"`
	// Workflow type started.
	Workflow string          `protobuf:"bytes,4,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Overlap  ScheduleOverlap `protobuf:"varint,5,opt,name=overlap,proto3,enum=backplane.v1.ScheduleOverlap" json:"overlap,omitempty"`
	// Created paused.
	Paused bool `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	// IANA time zone of a cron spec; empty is UTC.
	TimeZone string `protobuf:"bytes,7,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	// Random delay up to this added to every start.
	Jitter        *durationpb.Duration `protobuf:"bytes,8,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_backplanepb_v1_manifest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_backplanepb_v1_manifest_proto_rawDescGZIP(), []int{16}
}

func (x *Schedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schedule) GetSpec() isSchedule_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Schedule) GetCron() string {
	if x != nil {
		if x, ok := x.Spec.(*Schedule_Cron); ok {
			return x.Cron
		}
	}
	return ""
}

func (x *Schedule) GetEvery() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Spec.(*Schedule_Every); ok {
			return x.Every
		}
	}
	return nil
}

func (x *Schedule) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *Schedule) GetOverlap() ScheduleOverlap {
	if x != nil {
		return x.Overlap
	}
	return ScheduleOverlap_SCHEDULE_OVERLAP_UNSPECIFIED
}

func (x *Schedule) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Schedule) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Schedule) GetJitter() *durationpb.Duration {
	if x != nil {
		return x.Jitter
	}
	return nil
}

type isSchedule_Spec interface {
	isSchedule_Spec()
}

type Schedule_Cron struct {
	// Cron expression as Temporal reads it (5-7 fields, @daily, ...).
	Cron string `protobuf:"bytes,2,opt,name=cron,proto3,oneof"`
}

type Schedule_Every struct {
	// Fixed interval.
	Every *durationpb.Duration `protobuf:"bytes,3,opt,name=every,proto3,oneof"`
}

func (*Schedule_Cron) isSchedule_Spec() {}

func (*Schedule_Every) isSchedule_Spec() {}

var File_backplanepb_v1_manifest_proto protoreflect.FileDescriptor

const file_backplanepb_v1_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1dbackplanepb/v1/manifest.proto\x12\fbackplane.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x15schemapb/schema.proto\"\xee\x05\n" +
	"\bManifest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.backplane.v1.ConfigSectionR\x06config\x12+\n" +
	"\x06routes\x18\x06 \x03(\v2\x13.backplane.v1.RouteR\x06routes\x12+\n" +
	"\x11internal_services\x18\a \x03(\tR\x10internalServices\x12+\n" +
	"\x06events\x18\b \x03(\v2\x13.backplane.v1.EventR\x06events\x12(\n" +
	"\x05hooks\x18\t \x03(\v2\x12.backplane.v1.HookR\x05hooks\x126\n" +
	"\n" +
	"activities\x18\n" +
	" \x03(\v2\x16.backplane.v1.ActivityR\n" +
	"activities\x12 \n" +
	"\x02ui\x18\v \x01(\v2\x10.backplane.v1.UIR\x02ui\x12(\n" +
	"\x05nodes\x18\f \x03(\v2\x12.backplane.v1.NodeR\x05nodes\x12 \n" +
	"\vdescriptors\x18\r \x01(\fR\vdescriptors\x12@\n" +
	"\rsubscriptions\x18\x0e \x03(\v2\x1a.backplane.v1.SubscriptionR\rsubscriptions\x124\n" +
	"\tschedules\x18\x0f \x03(\v2\x16.backplane.v1.ScheduleR\tschedules\x124\n" +
	"\tworkflows\x18\x10 \x03(\v2\x16.backplane.v1.WorkflowR\tworkflows\x12<\n" +
	"\ttelemetry\x18\x11 \x01(\v2\x1e.backplane.v1.TelemetrySourcesR\ttelemetryJ\x04\b\x05\x10\x06R\x06staticR\adynamic\"\xa7\x01\n" +
	"\x17TelemetrySourceSelector\x12O\n" +
	"\bresource\x18\x01 \x03(\v23.backplane.v1.TelemetrySourceSelector.ResourceEntryR\bresource\x1a;\n" +
	"\rResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x10TelemetrySources\x12C\n" +
	"\tselectors\x18\x01 \x03(\v2%.backplane.v1.TelemetrySourceSelectorR\tselectors\"a\n" +
	"\rConfigSection\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12(\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaR\x06schema\x12\x12\n" +
	"\x04live\x18\x03 \x03(\tR\x04live\"b\n" +
	"\x04Node\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.backplane.v1.NodeKindR\x04kind\x12\x1a\n" +
	"\boptional\x18\x03 \x01(\bR\boptional\"\xe2\x02\n" +
	"\x05Route\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12+\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x17.backplane.v1.RouteKindR\x04kind\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bservices\x18\b \x03(\tR\bservices\x12\x1a\n" +
	"\aopenapi\x18\x05 \x01(\fH\x00R\aopenapi\x12\"\n" +
	"\vdescriptors\x18\x06 \x01(\fH\x00R\vdescriptors\x12\x1a\n" +
	"\agraphql\x18\a \x01(\fH\x00R\agraphql\x127\n" +
	"\x06bundle\x18\n" +
	" \x01(\v2\x1d.backplane.v1.APISchemaBundleH\x00R\x06bundle\x121\n" +
	"\x06policy\x18\t \x01(\v2\x19.backplane.v1.RoutePolicyR\x06policyB\b\n" +
	"\x06schema\"o\n" +
	"\x0fAPISchemaBundle\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n" +
	"\x05entry\x18\x02 \x01(\tR\x05entry\x122\n" +
	"\x06format\x18\x03 \x01(\x0e2\x1a.backplane.v1.SchemaFormatR\x06format\"\x85\x02\n" +
	"\vRoutePolicy\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12<\n" +
	"\fidle_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vidleTimeout\x12/\n" +
	"\x05retry\x18\x03 \x01(\v2\x19.backplane.v1.RetryPolicyR\x05retry\x12&\n" +
	"\x04cors\x18\x04 \x01(\v2\x12.backplane.v1.CorsR\x04cors\x12*\n" +
	"\x11max_request_bytes\x18\x05 \x01(\x04R\x0fmaxRequestBytes\"\x87\x01\n" +
	"\vRetryPolicy\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\rR\battempts\x12A\n" +
	"\x0fper_try_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rperTryTimeout\x12\x19\n" +
	"\bretry_on\x18\x03 \x03(\tR\aretryOn\"\xd1\x01\n" +
	"\x04Cors\x12\x18\n" +
	"\aorigins\x18\x01 \x03(\tR\aorigins\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\x12\x18\n" +
	"\aheaders\x18\x03 \x03(\tR\aheaders\x12%\n" +
	"\x0eexpose_headers\x18\x04 \x03(\tR\rexposeHeaders\x12 \n" +
	"\vcredentials\x18\x05 \x01(\bR\vcredentials\x122\n" +
	"\amax_age\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\"g\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06schema\x18\x02 \x01(\v2\x10.schemapb.SchemaR\x06schema\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"@\n" +
	"\fSubscription\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\"\xdf\x01\n" +
	"\x04Hook\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05input\x18\x02 \x01(\v2\x10.schemapb.SchemaR\x05input\x12(\n" +
	"\x06output\x18\x03 \x01(\v2\x10.schemapb.SchemaR\x06output\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xed\x02\n" +
	"\bActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05input\x18\x02 \x01(\v2\x10.schemapb.SchemaR\x05input\x12(\n" +
	"\x06output\x18\x03 \x01(\v2\x10.schemapb.SchemaR\x06output\x12.\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1a.backplane.v1.ActivityKindR\x04kind\x12?\n" +
	"\x0estart_to_close\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fstartToClose\x127\n" +
	"\theartbeat\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\theartbeat\x12/\n" +
	"\x05retry\x18\a \x01(\v2\x19.backplane.v1.RetryPolicyR\x05retry\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\x92\x01\n" +
	"\bWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05input\x18\x02 \x01(\v2\x10.schemapb.SchemaR\x05input\x12(\n" +
	"\x06output\x18\x03 \x01(\v2\x10.schemapb.SchemaR\x06output\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"5\n" +
	"\x02UI\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tsdk_major\x18\x02 \x01(\rR\bsdkMajor\"\xac\x02\n" +
	"\bSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x04cron\x18\x02 \x01(\tH\x00R\x04cron\x121\n" +
	"\x05every\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\x05every\x12\x1a\n" +
	"\bworkflow\x18\x04 \x01(\tR\bworkflow\x127\n" +
	"\aoverlap\x18\x05 \x01(\x0e2\x1d.backplane.v1.ScheduleOverlapR\aoverlap\x12\x16\n" +
	"\x06paused\x18\x06 \x01(\bR\x06paused\x12\x1b\n" +
	"\ttime_zone\x18\a \x01(\tR\btimeZone\x121\n" +
	"\x06jitter\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06jitterB\x06\n" +
	"\x04spec*q\n" +
	"\bNodeKind\x12\x19\n" +
	"\x15NODE_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_KIND_COMPONENT\x10\x01\x12\x18\n" +
	"\x14NODE_KIND_DEPENDENCY\x10\x02\x12\x17\n" +
	"\x13NODE_KIND_SINGLETON\x10\x03*c\n" +
	"\fSchemaFormat\x12\x1d\n" +
	"\x19SCHEMA_FORMAT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SCHEMA_FORMAT_OPENAPI\x10\x01\x12\x19\n" +
	"\x15SCHEMA_FORMAT_GRAPHQL\x10\x02*\x9a\x01\n" +
	"\tRouteKind\x12\x1a\n" +
	"\x16ROUTE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fROUTE_KIND_HTTP\x10\x01\x12\x13\n" +
	"\x0fROUTE_KIND_GRPC\x10\x02\x12\x16\n" +
	"\x12ROUTE_KIND_CONNECT\x10\x03\x12\x17\n" +
	"\x13ROUTE_KIND_WS_PROTO\x10\x04\x12\x16\n" +
	"\x12ROUTE_KIND_GRAPHQL\x10\x05*e\n" +
	"\fActivityKind\x12\x1d\n" +
	"\x19ACTIVITY_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACTIVITY_KIND_ACTIVITY\x10\x01\x12\x1a\n" +
	"\x16ACTIVITY_KIND_WORKFLOW\x10\x02*\xf9\x01\n" +
	"\x0fScheduleOverlap\x12 \n" +
	"\x1cSCHEDULE_OVERLAP_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SCHEDULE_OVERLAP_SKIP\x10\x01\x12\x1f\n" +
	"\x1bSCHEDULE_OVERLAP_BUFFER_ONE\x10\x02\x12\x1f\n" +
	"\x1bSCHEDULE_OVERLAP_BUFFER_ALL\x10\x03\x12!\n" +
	"\x1dSCHEDULE_OVERLAP_CANCEL_OTHER\x10\x04\x12$\n" +
	" SCHEDULE_OVERLAP_TERMINATE_OTHER\x10\x05\x12\x1e\n" +
	"\x1aSCHEDULE_OVERLAP_ALLOW_ALL\x10\x06B:Z8github.com/gopherex/backplane/backplanepb/v1;backplanev1b\x06proto3"

var (
	file_backplanepb_v1_manifest_proto_rawDescOnce sync.Once
	file_backplanepb_v1_manifest_proto_rawDescData []byte
)

func file_backplanepb_v1_manifest_proto_rawDescGZIP() []byte {
	file_backplanepb_v1_manifest_proto_rawDescOnce.Do(func() {
		file_backplanepb_v1_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backplanepb_v1_manifest_proto_rawDesc), len(file_backplanepb_v1_manifest_proto_rawDesc)))
	})
	return file_backplanepb_v1_manifest_proto_rawDescData
}

var file_backplanepb_v1_manifest_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_backplanepb_v1_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_backplanepb_v1_manifest_proto_goTypes = []any{
	(NodeKind)(0),                   // 0: backplane.v1.NodeKind
	(SchemaFormat)(0),               // 1: backplane.v1.SchemaFormat
	(RouteKind)(0),                  // 2: backplane.v1.RouteKind
	(ActivityKind)(0),               // 3: backplane.v1.ActivityKind
	(ScheduleOverlap)(0),            // 4: backplane.v1.ScheduleOverlap
	(*Manifest)(nil),                // 5: backplane.v1.Manifest
	(*TelemetrySourceSelector)(nil), // 6: backplane.v1.TelemetrySourceSelector
	(*TelemetrySources)(nil),        // 7: backplane.v1.TelemetrySources
	(*ConfigSection)(nil),           // 8: backplane.v1.ConfigSection
	(*Node)(nil),                    // 9: backplane.v1.Node
	(*Route)(nil),                   // 10: backplane.v1.Route
	(*APISchemaBundle)(nil),         // 11: backplane.v1.APISchemaBundle
	(*RoutePolicy)(nil),             // 12: backplane.v1.RoutePolicy
	(*RetryPolicy)(nil),             // 13: backplane.v1.RetryPolicy
	(*Cors)(nil),                    // 14: backplane.v1.Cors
	(*Event)(nil),                   // 15: backplane.v1.Event
	(*Subscription)(nil),            // 16: backplane.v1.Subscription
	(*Hook)(nil),                    // 17: backplane.v1.Hook
	(*Activity)(nil),                // 18: backplane.v1.Activity
	(*Workflow)(nil),                // 19: backplane.v1.Workflow
	(*UI)(nil),                      // 20: backplane.v1.UI
	(*Schedule)(nil),                // 21: backplane.v1.Schedule
	nil,                             // 22: backplane.v1.TelemetrySourceSelector.ResourceEntry
	(*schemapb.Schema)(nil),         // 23: schemapb.Schema
	(*durationpb.Duration)(nil),     // 24: google.protobuf.Duration
}
var file_backplanepb_v1_manifest_proto_depIdxs = []int32{
	8,  // 0: backplane.v1.Manifest.config:type_name -> backplane.v1.ConfigSection
	10, // 1: backplane.v1.Manifest.routes:type_name -> backplane.v1.Route
	15, // 2: backplane.v1.Manifest.events:type_name -> backplane.v1.Event
	17, // 3: backplane.v1.Manifest.hooks:type_name -> backplane.v1.Hook
	18, // 4: backplane.v1.Manifest.activities:type_name -> backplane.v1.Activity
	20, // 5: backplane.v1.Manifest.ui:type_name -> backplane.v1.UI
	9,  // 6: backplane.v1.Manifest.nodes:type_name -> backplane.v1.Node
	16, // 7: backplane.v1.Manifest.subscriptions:type_name -> backplane.v1.Subscription
	21, // 8: backplane.v1.Manifest.schedules:type_name -> backplane.v1.Schedule
	19, // 9: backplane.v1.Manifest.workflows:type_name -> backplane.v1.Workflow
	7,  // 10: backplane.v1.Manifest.telemetry:type_name -> backplane.v1.TelemetrySources
	22, // 11: backplane.v1.TelemetrySourceSelector.resource:type_name -> backplane.v1.TelemetrySourceSelector.ResourceEntry
	6,  // 12: backplane.v1.TelemetrySources.selectors:type_name -> backplane.v1.TelemetrySourceSelector
	23, // 13: backplane.v1.ConfigSection.schema:type_name -> schemapb.Schema
	0,  // 14: backplane.v1.Node.kind:type_name -> backplane.v1.NodeKind
	2,  // 15: backplane.v1.Route.kind:type_name -> backplane.v1.RouteKind
	11, // 16: backplane.v1.Route.bundle:type_name -> backplane.v1.APISchemaBundle
	12, // 17: backplane.v1.Route.policy:type_name -> backplane.v1.RoutePolicy
	1,  // 18: backplane.v1.APISchemaBundle.format:type_name -> backplane.v1.SchemaFormat
	24, // 19: backplane.v1.RoutePolicy.timeout:type_name -> google.protobuf.Duration
	24, // 20: backplane.v1.RoutePolicy.idle_timeout:type_name -> google.protobuf.Duration
	13, // 21: backplane.v1.RoutePolicy.retry:type_name -> backplane.v1.RetryPolicy
	14, // 22: backplane.v1.RoutePolicy.cors:type_name -> backplane.v1.Cors
	24, // 23: backplane.v1.RetryPolicy.per_try_timeout:type_name -> google.protobuf.Duration
	24, // 24: backplane.v1.Cors.max_age:type_name -> google.protobuf.Duration
	23, // 25: backplane.v1.Event.schema:type_name -> schemapb.Schema
	23, // 26: backplane.v1.Hook.input:type_name -> schemapb.Schema
	23, // 27: backplane.v1.Hook.output:type_name -> schemapb.Schema
	24, // 28: backplane.v1.Hook.timeout:type_name -> google.protobuf.Duration
	23, // 29: backplane.v1.Activity.input:type_name -> schemapb.Schema
	23, // 30: backplane.v1.Activity.output:type_name -> schemapb.Schema
	3,  // 31: backplane.v1.Activity.kind:type_name -> backplane.v1.ActivityKind
	24, // 32: backplane.v1.Activity.start_to_close:type_name -> google.protobuf.Duration
	24, // 33: backplane.v1.Activity.heartbeat:type_name -> google.protobuf.Duration
	13, // 34: backplane.v1.Activity.retry:type_name -> backplane.v1.RetryPolicy
	23, // 35: backplane.v1.Workflow.input:type_name -> schemapb.Schema
	23, // 36: backplane.v1.Workflow.output:type_name -> schemapb.Schema
	24, // 37: backplane.v1.Schedule.every:type_name -> google.protobuf.Duration
	4,  // 38: backplane.v1.Schedule.overlap:type_name -> backplane.v1.ScheduleOverlap
	24, // 39: backplane.v1.Schedule.jitter:type_name -> google.protobuf.Duration
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_backplanepb_v1_manifest_proto_init() }
func file_backplanepb_v1_manifest_proto_init() {
	if File_backplanepb_v1_manifest_proto != nil {
		return
	}
	file_backplanepb_v1_manifest_proto_msgTypes[5].OneofWrappers = []any{
		(*Route_Openapi)(nil),
		(*Route_Descriptors)(nil),
		(*Route_Graphql)(nil),
		(*Route_Bundle)(nil),
	}
	file_backplanepb_v1_manifest_proto_msgTypes[16].OneofWrappers = []any{
		(*Schedule_Cron)(nil),
		(*Schedule_Every)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backplanepb_v1_manifest_proto_rawDesc), len(file_backplanepb_v1_manifest_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backplanepb_v1_manifest_proto_goTypes,
		DependencyIndexes: file_backplanepb_v1_manifest_proto_depIdxs,
		EnumInfos:         file_backplanepb_v1_manifest_proto_enumTypes,
		MessageInfos:      file_backplanepb_v1_manifest_proto_msgTypes,
	}.Build()
	File_backplanepb_v1_manifest_proto = out.File
	file_backplanepb_v1_manifest_proto_goTypes = nil
	file_backplanepb_v1_manifest_proto_depIdxs = nil
}
