// @ts-check
module.exports = {
  docs: [
    'intro', 'quickstart',
    { type: 'category', label: 'Concepts and decisions', collapsed: false, items: [
      'concepts/architecture', 'concepts/contracts', 'concepts/decisions', 'concepts/dependencies',
    ] },
    { type: 'category', label: 'Go service SDK', items: [
      'sdk/go', 'sdk/components', 'sdk/configuration', 'sdk/routes', 'sdk/hooks', 'sdk/events', 'sdk/workflows', 'sdk/testing',
    ] },
    { type: 'category', label: 'Frontend and modules', items: [
      'sdk/frontend', 'sdk/modules', 'sdk/service-api',
      'reference/ui-kit', 'reference/components', 'reference/schema-forms',
      'reference/editors', 'reference/charts', 'reference/observability-ui', 'reference/platform-ui',
      'reference/module-template', 'reference/frontend-workspace',
    ] },
    { type: 'category', label: 'Operator guides', items: [
      'guides/console', 'guides/configuration', 'guides/wiring', 'guides/wiring-language', 'guides/events', 'guides/workflows',
      'guides/telemetry', 'guides/audit', 'guides/errors', 'guides/troubleshooting', 'reference/examples',
    ] },
    { type: 'category', label: 'Deployment and maintenance', items: [
      'deploying/overview', 'deploying/docker', 'deploying/gateway', 'deploying/security', 'deploying/availability',
      'deploying/releases', 'reference/configuration', 'reference/otlp', 'reference/development', 'reference/releases',
    ] },
    { type: 'category', label: 'Platform API', items: [
      'reference/api', 'reference/client',
      { type: 'category', label: 'Services', items: [{ type: 'autogenerated', dirName: 'reference/services' }] },
      'reference/audit', 'reference/observability-api', 'reference/errors', 'reference/browser-errors',
    ] },
  ],
};
